### ISSUE TITLE
Needed: Guide for Dynamic Platforms

### ISSUE THREAD

**Issue by jdtsmith** [homebridge/homebridge#1271]
I've studied the example dynamic platform plugin, but it seems to be somewhat incomplete, or at least difficult to parse.  Since it seems the syntax and call order for platforms are now rather different, it would be _very_ useful to have a concise list of elements that comprise a dynamic platform plugin that can discover, cache, and remove accessories.  Which platform methods are essential, and when and how are they called by homebridge?  What role does the new API play (vs. methods of the normal platform object)?  Is accessory caching handled automatically?  How does this interact (if at all) with hard-coded configuration in the config.json file?  Basically a simple how-to guide to replace the now defunct [platform programming guide](https://github.com/nfarina/homebridge/wiki/On-Programming-Platforms).  Thanks for this fabulous tool.

**Comment by dkrizic** [comment]
Take a look at homebridge-homematic, it works dynamically by querying the HomeMatic central for available devices.

**Comment by webdeck** [comment]
I don't think homebridge-homematic is using the latest platform methods that allow caching and control of reachability of accessories.  I would like to see an updated guide as well so that I can update my plugin to the latest standard and avoid having all of my accessories wind up in the default room whenever something is unreachable temporarily.

**Comment by jdtsmith** [comment]
_**Calling All Dynamic Platform Authors**_

I'm reopening this with the hopes of attracting the help and wisdom of any authors experienced with creating **Dynamic Platforms**.  There is unfortunately very limited information on programming dynamic platforms, and as a result, very few plugins in the wild are written as dynamic.  But my understanding is that dynamic plugins are _better for almost all use cases_, leading to faster homebridge startups, and (especially) eliminating the "plugin has gone missing and gets reassigned to a default room and lost from scenes and automations" problem that many have grappled with.  So it seems that if most plugins were updated to be dynamic platforms, this would be a major improvement, even for simple plugins. 

[Frédéric Barthelet's blog post](http://www.theodo.fr/blog/2017/08/make-siri-perfect-home-companion-devices-not-supported-apple-homekit/) is a great intro for non-dynamic plugins; we need something similar for dynamic platforms.  

For now I've put a note at the top of the[ incomplete wiki page](https://github.com/nfarina/homebridge/wiki/On-Programming-Dynamic-Platforms) documenting dynamic platforms.  

Things I think would be important to document (feel free to add to the list!):

1. How dynamic and non-dynamic platforms differ.  When you'd prefer one over the other. 
1. How and when accessories are cached and restored from cache.
1. Best practices for discovering accessories and checking against the stored list for adds/deletes/updates.  What if a given accessory disappears?  What if an existing accessory's config changes?  What if a new accessory appears on the network?
1. Best practices for storing and updating configuration information in a given accessory.
1. Which additional callbacks does homebridge need to make a platform dynamic?  I.e. what is the "minimal dynamic platform"?

So please consider sharing your hard earned knowledge, and tagging anyone whom you think could contribute!  Perhaps @ebaauw (Sonos zp dynamic platform) and @chrisjshull (Nest) could lend some of their expertise? Others?

Thanks to all who can contribute!

**Comment by ebaauw** [comment]
I'm trying to implement all my "best" practices in [homebridge-lib](https://github.com/ebaauw/homebridge-lib), so my actual plugins only have to deal with the devices they're exposing.  My plugins using the dynamic platform accessory model (incl. homebridge-zp) are all based on homebridge-lib; my other plugins are still using the static platform accessory model.  I plan to convert these eventually, but really want to iron out all quirks before touching homebridge-hue (which has by far the most users).

The code in homebridge-lib is self-documenting; if you run `jsdoc` it generates the documentation, incl. the interface to homebridge.  I haven't published the generated documentation.  I tried setting up a WiKi at first, but lack the discipline to maintain it.  The tutorial in the documentation should get you started.

Note that homebridge-lib is work in progress, as I'm converting my plugins.  It's pure Javascript; I'm not yet sure where I stand on TypeScript.

As to your questions:
> 1. How dynamic and non-dynamic platforms differ. When you'd prefer one over the other.

The differences between the two models are quite big.  In the static model, your plugin returns a number of accessory delegates to homebridge, through the `accessories()` callback.  Homebridge creates the `Accessory` instance from the delegate, using the delegate's `uuid_base` property and `getServices()` method.  This happens _before_ homebridge starts its HAP server.

In the dynamic model, your plugin creates `PlatformAccessory` instances, which you register and unregister with homebridge dynamically, _after_  homebridge has started its HAP server.  The `Accessory` instance is still created by homebridge, but you need to add each `Service` individually, using the `PlatformAccessory` methods (which after some housekeeping and checking call the corresponding `Accessory` methods).

When I first started working on homebridge-hue (many years ago, before I published it to GitHub), it actually supported both models, setting just a single constant to select the model.  Back then, I had stability issues with the dynamic model that I couldn't resolve (or even understand), so I decided on the static model.  Today, I would prefer the dynamic model, because of it's features, but it's more complicated for the developer.  I'm slowly converting all my existing plugins to be using the dynamic model, and am using the dynamic model for new plugins.

> 2. How and when accessories are cached and restored from cache.

`cachedAccessories` is used only with the dynamic platform model.  The cache should be updated when registering or unregistering `PlatformAccessory` instances, and before homebridge exits.  I think it's updated when homebridge crashes (with my PR #2190), but before the plugin callbacks (#1905) are called.  homebridge-lib actually tells homebridge to flush the cache every 10 minutes.

You can add your own stuff to the cache, using the `context` property of `PlatformAccessory`.  homebridge-lib even stores the entire fakegato history there, so homebridge-ws no longer needs separate history files.  I'm not sure yet if this will scale to homebridge-hue.  I plan to store the Hue bridge username (API key) there, so there's no need to edit config.json manually.

> 3. Best practices for discovering accessories and checking against the stored list for adds/deletes/updates. What if a given accessory disappears? What if an existing accessory's config changes? What if a new accessory appears on the network?

HomeKit will delete any previously exposed accessory when the HAP server starts without exposing the accessory.  In the static model, this causes an issue when the plugin doesn't re-discover the device and fails to return the corresponding delegate through the `accessories()` callback.  If the device is re-discovered again after restarting homebridge, HomeKit sees it as a new accessory, in the default room, having lost any group, scene, and automations.

In the dynamic model, previously exposed accessories are loaded from cache, _before_ the HAP server starts.  homebridge will call the platform's `configureAccessory()` method for each restored `PlatformAccessory`, and issue a `didFinishLaunching` event after the HAP server has started.  Note that the entire `Accessory`, `Service` and `Characteristic` structure is restored, so you don't need to re-create the services and characteristics.

The `PlatformAccessory` instances restored by homebridge are "orphaned"; your plugin needs to re-discover the device (based on the info you places in `context`) and link the device and the restored accessory.  It's up to your plugin how to handle disappearing accessories.  You can unregister them, but when they re-appear and are re-registered, HomeKit will treat them as new accessories, or you can mark your accessory as unavailable.  How best to do that is a different discussion altogether.  I don't have a best practice here: homebridge-ws takes the list of weather stations from config.json, removing any restored accessory which is no longer specified; homebridge-zp keeps the accessories around, assuming the zone player is rebooting or temporarily unavailable.

> 4. Best practices for storing and updating configuration information in a given accessory.

Don't change HomeKit configuration data once the accessory has been exposed.  I think the HAP spec forbids this, except after a firmware update.  Besides, HomeKit really doesn't like configuration changes, showing accessories as not responding for hours if you're unlucky, while the configuration changes are synced between all your devices over iCloud.

> 5. Which additional callbacks does homebridge need to make a platform dynamic? I.e. what is the "minimal dynamic platform"?

Obviously, you need to call `registerPlatform()` with the fourth argument set to `true`.  And your platform instance needs to expose a `restoreAccessory()` method.

**Comment by jdtsmith** [comment]
Really really useful information, thanks @ebaauw.  For a config change I was imagining an existing device getting a new IP address assigned.  Should it be destroyed and recreated as an orphan?  I suspect not, since HomeKit probably does not care about that internal config.   But of course you want to save the new IP address so it can be cached.   

But what if the internal config maps to a HomeKit-visible change?  As a concrete example, imagine the list of inputs on a new television service changes due to users changing it on their TV.  Can an accessory in a dynamic platform survive such a transformation?

**Comment by ebaauw** [comment]
OK, by “config” change I understood changing the HomeKit services, characteristics, and/or characteristic properties.  Basically, any change other than characteristic values.

Make sure to base the accessory uuid on something static, like a mac address or serialnumber, rather than on something changeable, like an IP address or (user assigned) device name.  Handling a changed IP address is tricky: you’ll probably re-discover the device at a new IP address, query it for its unique id, see that the corresponding `PlatformAccessory` has already been registered, and link the re-discovered device to the existing accessory.

For honebridge-zp, I also need to handle a zone player reboot.  The subscriptions homebridge-zp makes with the zone player for notifications are lost on reboot.  Luckily, Sonos exposes a boot sequence number.

The TV inputs is an interesting case.  I ended up exposing a fixed number of 20 channels (input services) for each TV accessory linked to a zone.  When the user changes their Sonos favourites, I only update the visibility and name of the pre-defined inputs, only characteristic values.  Still, the Home app has a hard time reflecting those changes in a timely manner.  Somehow, HomeKit doesn’t expose TV accessories to other HomeKit apps...

**Comment by jdtsmith** [comment]
Thanks again @ebaauw. Do you know of others to tag who are experienced with dynamic platforms and could expand on any of this?  How do “linked services” fit into this picture btw?

**Comment by ebaauw** [comment]
You might want to check with @NorthernMan54 (he already re-opened this issue, so I suppose he's seen it) and @oznu.

I never quite understood the use case for linked services.  Sometimes HomeKit requires services to be linked (notably for television accessories), sometimes it doesn't.  I haven't been able to discover any pattern as to when.  Same for the primary service.

**Comment by NorthernMan54** [comment]
For linked services the only place I have seen it used is part of the Television accessory, and for linking the input service to the television service

For primary service, I have tried this with a couple of my plugins and did not notice any change in behaviour.  I was trying it in regards to the grouping issues with iOS 13, and did not notice any impact.

**Comment by NorthernMan54** [comment]
@ebaauw You mentioned a method `restoreAccessory` that a platform needs to expose, I looked at the source code and could't find it.  Is it possible you mean `configureAccessory`?

```
Obviously, you need to call registerPlatform() with the fourth argument set to true. And your platform instance needs to expose a restoreAccessory() method.
```

**Comment by ebaauw** [comment]
My bad.  Indeed, it’s `configureAccessory`.

**Comment by jdtsmith** [comment]
I guess `configureAccessory` is only called on accessories restored from cached ?  Is there any API documentation for it?  Is its main job is to merge device config from the `config.json` file, as well as anything auto-discovered, with the version restored from disk?

Just to be concrete, perhaps we could put together a short HOWTO for dynamic plugins.  Here's a start... please edit/correct/append.

+++++

Dynamic platforms represent a more modern approach to programming`homebridge` accessories.  Dynamic platforms can register/de-register devices at any time after launch finishes, even based on information not available when `homebridge` starts.  Dynamic platforms can even be "zero config", requiring nothing from the user other than installation.  Dynamic platform device accessory information is automatically cached and reloaded on restart, which speeds up homebridge launch and reduces the likelihood that accessories get re-assigned rooms or removed from Homekit scenes.   Creating a dynamic platform is somewhat different than the older config-based platforms.  

To create a dynamic platform: 

1. Specify `true` as the final argument of `registerPlatform`.
1. Provide a `configureAccessory` method which takes a single argument: `accessory` (a `PlatformAccessory` object, restored from the cache). _[NEEDED: Object fields and events emitted by `PlatformAccessory`'s; also a concise description of the main purpose of `configureAccessory`]_ 
1. In your dynamic platform constructor (the 3rd argument you specify in `registerPlatform`), save the `api` object passed in.  This object is what will be used to register discovered accessories dynamically.  This is a substitute for providing an `accessories` method in the older style of platform design.  
1. Wait for a `'didFinishLaunching'` event from the `api` object, and only then (after homebridge has finished launching), begin registering devices.
1. To avoid duplicate devices, you need to identify some means of uniquely identifying a device (e.g. a MAC address or serial number or some other unique identifier).  This information can be saved (with any other useful info) in the `context` field of the accessory, which will be saved and restored from cache.
1. The `api` object provides another pair of useful methods: `registerPlatformAccessories` and `unregisterPlatformAccessories`, which should be used for dynamic addition and removal of accessories. 
1. Dynamic device discovery should ideally merge together i) "hard-wired" accessories specified by the user in their `config.json`, ii) cached accessories which are reloaded for dynamic platforms automatically by homebridge , iii) (optional) auto-discovered accessories, e.g. via a local network discovery (Bonjour/UPnP), pulling information from a web service, querying another hub, etc. Care must be taken to ensure no duplicate devices, by comparing the unique identifier. 
1. ???

**Comment by justme-1968** [comment]
some general remarks:

i would like to use the dynamic part to add and remove accessories on the fly, but i don't like the concept of cached accessories for my purpose. 

the reason for this is: i see homebridge-fhem as just another frontend to the fhem home automation system. fhem ist the master and the system to maintain state. so having a cache is redundant and even potentially a source for conflicts. the same can probably be said for other home automation systems.

it would actually be more code to check that the cached state (number and type of services and characteristics and their current values) is identical to the 'real' current state in the ha system and to correct differences (add, remove, change values) than to just recreate the accessories from scratch from the 'source of truth' ie. the ha system.

so the question would be: is there a way to disable the cache for dynamic platforms or is there a way to dynamically add accessories to the 'old style' non-dynamic platforms.

**Comment by ebaauw** [comment]
Technically, your plugin could unregister all accessories on shutdown and flush the cache.  Alternative, it can unregister the restored accessories.  I think this should work from `configureAccessory`; if not do it from the `didFinishLaunching` event handler.

I don’t think you appreciate the function of the cache: if the homebridge server starts without any accessories exposed, HomeKit removes the accessory.  When later, the accessory is exposed again, HomeKit treats it as a new accessory, losing any assignments to groups, scenes, rooms, and automations.  This is definitely not what you want.

I have been fantasising about a hybrid model, where a platform plugin exposes both `accessories()` and `configureAccessory()`.  This would allow the plugin to delay the startup of the homebridge HAP server, retuning a list of accessories to be exposed as well as to add or remove accessories dynamically.  My main use case would be during development, deleting a polluted `cachedAccessories` but keeping the room assignments, etc.  I have a very dirty hack in homebridge-lib which sort of accomplishes this: homebridge-lib registers as a static platform plugin and only calls the `accessories()` callback after all dynamic platform plugins have emitted an `initialised` event.

**Comment by justme-1968** [comment]
i never ever had a single problem with lost assignments. all devices in homebridge-fhem have persistant unique ids. even if my development system is not running for some time if i start it homekit will assign the assessors back to the configured rooms. 

the only problems that apear from time to time are problems during lining or unlinking a bridge. then one can be forced into changing the username. but as this implicitly invalidates the cache there is also no advantage in this case.

such a mixed mode would be nice. that would allow me to dynamically add new devices without a restart.

**Comment by ebaauw** [comment]
> i never ever had a single problem with lost assignments.

Because the homebridge HAP server starts _after_ accessories exposed by static platform plugins are loaded.  It starts _before_ dynamic platform plugins register (new) accessories.

**Comment by richierockskool** [comment]
I need this reopened to assist platformAccessory.ts for https://github.com/richierockskool/homebridge-inkbird-wifi-gateway
