### ISSUE TITLE
Offline devices don't appear as offline in homekit

### ISSUE THREAD

**Issue by robbgrrr** [homebridge/homebridge#1732]
I'm running Homebridge on a Mac connecting to 6 devices through a Mosquitto MQTT broker installed on the same machine. The devices are Sonoff (ESP8266) flashed with Tasmota MQTT enabled firmware.
I'm using homebridge plugins by macwyznawca and most everything is working well; I can control state of the devices through Homekit and get real-time state of the device reported back to Homekit when the device is toggled manually. 

My expectation is that when a device goes offline through a loss of power or network, Homekit should show the device as "offline" or some such. But there is no outward indication that the device is in trouble, in fact Homekit still lets me toggle the button on/off and behaves as though all is ok. 
I can see by monitoring the LWT topic that mosquito does report it as "offline" and if I open the "details" page for the device in Homekit I can see that "status active" = No.

Is this normal?
Any suggestions?

Thanks very much,

**Comment by NorthernMan54** [comment]
I would suggest opening an issue against the plugin, as this issue is with the plugin itself and not homebridge.  Also, you can mention this enhancement to homebridge/HAP-NodeJS which enhances a devices ability to report “not responding”.

https://github.com/KhaosT/HAP-NodeJS/pull/556 <https://github.com/KhaosT/HAP-NodeJS/pull/556>
