### ISSUE TITLE
Loosing instances and config

### ISSUE THREAD

**Issue by beatpaul** [homebridge/homebridge#2307]
Hi!

I run homebridge with multiple instances (5) on a mac and I have some real strange behavior:

When i update any plugin used in the first instance i loose all the other instances (homebridge-bridges and accessories, etc. ) in my home app.
The strange thing is, that the first instance still shows up, but not with the latest setting, it shows up with some old settings and old scenes ...

so whenever i update some plugin from the first instance i have to change the username of the missing instances re-add them and do all the config work. --> which really sucks :(

Would be great if anyone has an idea !

@ebaauw: you helped me with adding instances once (thx a lot!!) maybe you have an idea about this too :)

thx
Paul

**Comment by ebaauw** [comment]
You are using the `plugins` setting in config.json to load only the plugins you need per instance, aren’t you?  Otherwise, updating a plugin might impact multiple instances.  Did you double-check that each Homebridge instance is using a different `persist` directory?

What do you mean by "loose"?  Do the accessories disappear spontaneously from HomeKit?  Or are they stuck in non responding state?  HomeKit really doesn’t like configuration changes.  After updating plugins (or even changing `config.json`) causing them to expose accessories differently, it can take up to half an hour or longer before HomeKit displays the new configuration.  Better check your fastest iOS device or Home on macOS first.  Don't make any other changes until the new configuration has been propagated to all devices (wait until the next morning).

In my experience, you only have to change the username after HomeKit has repeatedly banned an accessory (i.c. Homebridge instance) because of non-compliance.  Most cases of missing homebridge instances are caused by a mismatch between the HomeKit configuration on your iOS device and the homebridge state in `persist`, or by Bonjour issues.

**Comment by beatpaul** [comment]
> You are using the plugins setting in config.json to load only the plugins you need per instance, aren’t you? Otherwise, updating a plugin might impact multiple instances. Did you double-check that each Homebridge instance is using a different persist directory?

I use the plugins setting in config.json so only the necessary plugins are loaded for each instance
I run each instance as a service from different folders--> persist folders are in each of them
I run each instance with the -u option except the first instance (may this be the problem?)
How can i check / change the persist folder? 

> What do you mean by "loose"? Do the accessories disappear spontaneously from HomeKit? Or are they stuck in non responding state? HomeKit really doesn’t like configuration changes. After updating plugins (or even changing config.json) causing them to expose accessories differently, it can take up to half an hour or longer before HomeKit displays the new configuration. Better check your fastest iOS device or Home on macOS first. Don't make any other changes until the new configuration has been propagated to all devices (wait until the next morning).

I checkt now after half a day all instances except the first one are lost - by this i mean that not even the (home)bridges ( symbol with the 3 dots) of instance 2 to 4 are showing up in the home app

> In my experience, you only have to change the username after HomeKit has repeatedly banned an accessory (i.c. Homebridge instance) because of non-compliance. Most cases of missing homebridge instances are caused by a mismatch between the HomeKit configuration on your iOS device and the homebridge state in persist, or by Bonjour issues.

to change the username is the only way for me to re-add the missing instances and i have to add all accessories and put them in the correct room, order etc.
Is there a way to do a backup of all homekit?

@ebaauw: don't you have something like a donate button  - for a couple of bears et least:)
I really appreciate your help!
