### ISSUE TITLE
Disable default "on" notifications for all new accessories

### ISSUE THREAD

**Issue by rducky88** [homebridge/homebridge#2360]
Here's hoping there's a solution...

All new security type accessories (locks/garage etc) added to Homebridge appear in the 'Home' app with the default notification state selected to "on". Is there a way to override this default setting for newly added security devices.

This seems to be an Apple default for security purposes. Want to configure a number of door locks with Homebridge, but the thought of having to disable notifications for every door, for every Home app member, on every one of their devices is just nightmarish!

Any solution out there whilst still keeping it as a "Lock" and not a switch etc...?

**Comment by NorthernMan54** [comment]
Have you read Apple's HAP spec, this is not mentioned.  And as Homebridge is based on this API, not feasible

**Comment by rducky88** [comment]
I have not, thanks for confirming - I thought that may be the case. The door locks will remain as standards switch then... having to disable the door lock notifications for twenty odd doors, for every home member, on every one of their devices is just too much.

Thanks again.

**Comment by jvmahon** [comment]
> I have not, thanks for confirming - I thought that may be the case. The door locks will remain as standards switch then... having to disable the door lock notifications for twenty odd doors, for every home member, on every one of their devices is just too much.
> 
> Thanks again.

You may already realize this, but ...
Implementing door locks as standard switches can be advantageous, but can also introduce some security concerns.  As an example of an advantage, consider that barriers (doors) and locks generally require that your iPhone be unlocked in order to activate them, while switches do not. This means that if you are using a geofenced automation, that automation won't work if the phone is locked and the device you are trying to control is a lock or door. By implementing as a switch, you can use geofencing on the door/lock. So, for example, I use switches as a way to control locks and garage doors such that, when I drive away from my house, the doors lock / close (even if the phone is locked). Similarly, as I approach my driveway, the garage door automatically opens. The problem, of course, is that Siri now thinks the lock is a switch so you have to say turn on / turn off instead of lock, and you are avoiding other security / safety features that are associated with how locks / doors are managed by HomeKit.
