### ISSUE TITLE
ERROR: uncaughtException: Cannot add a bridged Accessory with the same UUID as another bridged Accessory:

### ISSUE THREAD

**Issue by sebastienb** [homebridge/homebridge#2415]
### Expected Behavior
After installing the smart thing plugin I proceed to install a second plugin, the Kevo plugin or the Smart Q plugin. I'm installing all the same plugins i had on a previous homebridge hub

### Current Behavior
After installing the second plugin no matter which i install first i get the error listed in the title. I'm able to get past the error by removing the Homebridge hub from my home app and re-adding it and restarting homebridge.

### Versions

- **Homebridge**:  0.4.50
- **Node**:       v12.15.0
- **OS**:         Not sure, using a Docker image in the default options

### Configuration

```json

```

### Homebridge Log / Command Output

```
ERROR: uncaughtException: Cannot add a bridged Accessory with the same UUID as another bridged Accessory:
```

**Comment by Supereg** [comment]
A Bridge cannot have two Accessories with the same UUID. So one of your plugins seem to setup an accessory which does not have a unique UUID.
This problem is caused my some of your plugins, maybe one, maybe a combination of more than one.
What is necessary to find the cause is your **CONFIGURATION** and also a more detailed **LOG OUTPUT** to identify the plugin causing the problem.
