### ISSUE TITLE
Cameras with DynamicPlatformPlugin

### ISSUE THREAD

**Issue by platini76** [homebridge/homebridge#2530]
hello, thanks for your work!
can you please specify which plugins are compatible with this?

Cameras can now be added to the bridge using a DynamicPlatformPlugin and the methods configureCameraSource or configureController of the PlatformAccessory (removing the need to create an external accessory)

**Comment by Supereg** [comment]
We don't have a list of plugins which already support bridged cameras. If you are just searching for an example you may want to look at the `bridged-camera-example-typescript` in the [homebridge-examples](https://github.com/homebridge/homebridge-examples) repo (although this is written in Typescript and not plain Javascript.

Otherwise you may just ask the plugin owner directly when they plan to support this feature.

**Comment by platini76** [comment]
no I am trying to configure my own camera.

**Comment by Supereg** [comment]
Then as I said, have a look at the example.
