### ISSUE TITLE
Problem with Automation 

### ISSUE THREAD

**Issue by Galiwyx** [homebridge/homebridge#2622]
Hello =)

I have some problem with an automation. I use Homebridge on Docker, with DeCONZ (Conbee II usb stick) and Homebridge-Hue. Most of my automations works perfectly but one drives me crazy for one week :D 

I use a Xiaomi Sensor on my door. When I open the door, a light in the corridor should light up. The problem is that it works only after the second activation or more. I noticed that when my iPhone is unlocked it works more often.

Door closed > Door opened > Light off > Door close > Dorr opened > lights on.

In the Homebridge logs, I can see that the Xiaomi sensor activates immediately but not the light : 

**Logs**

[7/4/2020, 9:07:35 PM] [Hue] Porte entrée: set homekit contact from 0 to 1
[7/4/2020, 9:07:37 PM] [Hue] Porte entrée: set homekit contact from 1 to 0
[7/4/2020, 9:07:39 PM] [Hue] Porte entrée: set homekit contact from 0 to 1
[7/4/2020, 9:07:39 PM] [Hue] Entrée - Lampe: homekit on changed from 0 to 1
[7/4/2020, 9:07:41 PM] [Hue] Porte entrée: set homekit contact from 1 to 0

* **Node.js Version**:  v12.18.2
* **NPM Version**: v6.14.5
* **Homebridge Version**: v1.1.1
* **Operating System**: Docker
* **Process Supervisor**: Docker

Thank you =)

**Comment by Galiwyx** [comment]
Probleme still here.

**Comment by ebaauw** [comment]
> DeCONZ (Conbee II usb stick) and Homebridge-Hue.

If both the sensor and the light are connected to deCONZ, use deCONZ rules instead of HomeKit automations.  Quicker and far more reliable.

> The problem is that it works only after the second activation or more.

HomeKit automations failing to trigger are almost always caused by the Home hub failing to subscribe to change notifications by the accessory (i.c. Homebridge) that triggers the automation.  Sometimes you see this in Home or another HomeKit app as well: updated values aren’t pushed to the app, but do show when you refresh the screen.

> I noticed that when my iPhone is unlocked it works more often.

When you have a HomeKit app open on your phone, it might receive the updated value, and sync that to the Home hub over iCloud.  You might notice a delay before the automation is triggered in this case.

**Comment by Galiwyx** [comment]
Thank you for your reply. 

Unfortunately lights are on IKEA hub and sensors on Deconz. I’ll try to add light on Homebridge hue and create automation through Deconz. 

On the other hand, even if the light does not come on, the sensor (doo sensor) is triggered instantly on homebridge.

I use an iPad Air 3 as HUB, maybe isn’t good as an HomePod or Apple TV ? 

I really hope it will work.

**Comment by Galiwyx** [comment]
Unfortunately, scenes cannot be created with door sensor like Aqara Windows / door sensor. I only can add Motion sensor.

**Comment by ebaauw** [comment]
Use the API to create the rules manually instead of Phoscon.
