### ISSUE TITLE
Ive seen its pretty common to get the EADDRINUSE error, because the port is being used, so in Win10, can i change the port homebridge uses?

### ISSUE THREAD

**Issue by bmcdtt** [homebridge/homebridge#2623]
**Describe Your Problem:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
You can set it to be whatever you like in the `config.json`.

https://github.com/homebridge/homebridge/blob/master/config-sample.json#L7

The main reason to get the `EADDRINUSE` error is because Homebridge is already running, so changing the port may not actually resolve the underling issue you are facing.
