### ISSUE TITLE
network visibility on ISP modem

### ISSUE THREAD

**Issue by lukasa1993** [homebridge/homebridge#2673]
hello, so i am using homebridge extensively i had my homebridge server always connect to me WIFI router but now i needed to connect directly to ISP Router and when i do my accessories aren't available and if i connect back to wifi router they come online instantly so what should i ask for my ISP to open so it works ? all with in local network…

**Comment by lukasa1993** [comment]
isn't a bug miss clicked…

**Comment by masterfordev** [comment]
That is because you are using a subnet (wifi router). You have to find some way to make visible the devices of your subnet (wifi router) from your isp router.

**Comment by lukasa1993** [comment]
@masterfordev it wasn't subnet, it appears that my isp blocks multicast and MDNS doesn't work

**Comment by angyalZK** [comment]
I think same was my problem with iOS 14 beta and tvOS 14 beta. The issue is not with HomeBridge or with ISP, Apple changed something with iCloud. Automations not worked also. My solution was sign out with iCloud on tvOS and iOS too, and sign in back. That works for me, HomeBridge, HomeKit, and automations also works well again.
