### ISSUE TITLE
Issues with tvOS 14.2 / iOS 14.2 - Device is not compatible

### ISSUE THREAD

**Issue by MichaelMrak** [homebridge/homebridge#2715]
Are there any issues with HomeBridge (latest version) and tvOS 14.2 / iOS 14.2? All my devices report "no answer" ("keine Antwort") in red letters. But HomeBridge works fine and i can also switch all devices in the webbrowser frontend of HomBridge (homebridge-config-ui-x) without any problems. 

I tried to remove and add HomeBridge again (using a new username) to HomeKit but get an errormessage "Device is not compatible" (Gerät ist nicht kompatibel). 

For testing I also removed HomeBridge via the Home App. Then i wanted to add HomeBridge again (changed username und PIN in advance to to avoid conflicts). Now i cannot HomeBridge add anymore, it is rejected with the notification "device is not compatible" (see picture).

An advice?

<details>
  <summary>Click to expand for pictures!</summary>
  
![IMG_0506](https://user-images.githubusercontent.com/52258219/98449234-38cd6b80-2132-11eb-8df5-7027d4dd84a5.PNG)

![IMG_0505](https://user-images.githubusercontent.com/52258219/98449239-3b2fc580-2132-11eb-84ca-13119882bb58.PNG)
</details>

**Comment by composerkaumann** [comment]
I have Homebridge running on Ubuntu server and AppleTV HD as home hub, running TvOS 14.2. No issues so far, everything shows up and works.

**Comment by MichaelMrak** [comment]
Thanks for the response. I have now installed Homebridge on my old Mac mini and works fine. So the "not compatible" error must somehow be in the Raspberry Setup. I will try to reinstall Homebridge there.

**Comment by FSTNDonald** [comment]
More details ...
I am stuck by similar HK "no response" erratic behaviour. Rebooting anything restores connectivity for some hours, afterwards periods of "no response" happen, at the end the HB devices are off-line in HK.

Testbed (all running latest updates):
1.) HB on orangepizero, Debian (SUNXI kernal), HUE plugin
2.) Aqara HUB
3.) CCU3, redmatic, homekit addon
4.) 2 x ATV
5.) iphone
6.) HK, connected to icloud on ATVs and iphone

Actions:
1. disable IPV6 in LAN switches / router ( ref. github https://github.com/homebridge/homebridge/issues/1277 )
2. on opizero use nmtui to disable IPV6
3. on opizero change eventedhttp.js as described (... add '0.0.0.0' host)
4. netstat on opizero to confirm, that HAP ports are tcp and not tcp6

Result:
R1: IF (iphone in local LAN) THEN (no more connections lost, i.e. HB devices responding any time)
R2: IF (iphone connected to LTE) THEN ((erratic connection behaviour of HB devices) AND (stable connection of Aqara and redmatic devices))
As remote access (by LTE) is bridged the way  iphone -- icloud -- ATVs -- HK bridges, it is obvious, that only HB is in trouble speaking to ATVs.
Snipped netstat output confirms, ref trace at end. ATVs are 192.168.0.20, ...21:

My experience with HAP protocol is limited, any advice to investigate further ...?

![image](https://user-images.githubusercontent.com/55955113/98682562-5a159e00-2364-11eb-806e-06cca0288005.png)

**Comment by composerkaumann** [comment]
I had "no response" issues when I had HB running in Docker environment on Synology DiskStation. This was also combined with automations working/not working, the behaviour was quite erratic. I tried to resolve the issue and installed Ubuntu server directly on old MacBook Pro 4,1. Now everything works fine BUT sometimes when I am not in home LAN, "no response" error still appears. This can resolved by establishing VPN connection to home LAN, then everything responds just fine. The weirdness is that approaching my Homekit setup from WAN side sometimes results with "no response" messages and sometimes not. Haven't identified the pattern yet.

**Comment by FSTNDonald** [comment]
Whenever iphones / ipads / ipods booked into icloud (with same account) and HK enabled (account -> icloud -> apps listing) are connected to local WLAN everything is fine - netstat excercise reveals plenty of established connections for those devices.
Just do the test and dis-able WLAN on any of these. That devices with WAN connectivity (SIM card inserted) will see your home via icloud - atv - hb - connected sub-bridges (plugins)  ...  My finding: ports from atv to hb are NOT established stable, but drop and reconnect (with new ports, ref. log picture) erratically.
It is not due to atv, other platforms with open-source / linux hap (redmatic, aqara) perform, just hb has trouble.
I like the idea of an open source integrator like hb very very much, but 'home automation' is trustness, i.e. no tolerance for lockers etc. working eratically.

**Comment by x5nder** [comment]
I have the exact same problem since earlier this week, with nothing changed in the configuration except for updating a few plugins. Homebridge is running fine, all accessories are available. But Home on my iPhone or iPad show 'no response' for all Homebridge devices, until I actually tap an accessory once or twice. Then it connects and performs the action. Sometimes, all other accessories come back right after that, sometimes they don't, but they can all be controlled by tapping.

**Comment by HenriApperloo** [comment]
Issues with Iphone 8 iOS 14.2 (18B92)- Device is not compatible
I have maybe the same problem, it is a new installation of Homebridge

HomeBridge v1.1.6 
Node.js Versie v14.15.1
Npm versie v6.14.8
Raspberry Pi Zero W

- The Iphone reconize the qr-code, 
- I add the bridge
- I receive a notification 'Non-certified accessory'
- I am going on, I don't cancel it.
- I see a screen with connecting with bridge
- later.... x minuts
- I see a screen with a time-out, Not possible to add an accessory

-When I try again, then I receive the message 'Bridge already know'. But I can't find the bridge in HomeKit

ps. translated from dutch

**Comment by gzeel** [comment]
The same over here. New Homebridge installation on a ESXI VM, in the same LAN. 
Can add the first 3 accessoires, than crashes and accessoires are on “Not responding” status.

**Comment by Supereg** [comment]
Can anyone of you (if you feel like capable of fiddling around with stuff) test if your issue persist with the latest homebridge 1.3.0 **beta** (installable via the UI or using something like `sudo npm install -g homebridge@beta`).

Also would be interesting on which version of homebridge you are experiencing the issues. Some stated 1.1.6, some didn't specify anything.

There are really two issues stated in this thread:
* "No response": If you are running 1.2.x and experience that, it may well be that 1.3.0 beta will fix that for you (mdns related issues). Should this also happen with 1.1.6 it might well be that this can also be caused by a specific plugin. 1.3.0 has some additional sanity checks trying to expose misbehaving plugins. You might try the beta as well and check if there are any warnings printed to the console.
* "Device not compatible": This error is most likely related to a "misbehaving" plugin (or some sort of bug in those). As stated above, the improved sanity checking in the latest beta might help to expose the issue behind that.

**Comment by composerkaumann** [comment]
In addition to having two separate issues in this thread, we also have the third: The Title (issues with TvOS14.2) which is misleading.
That aside- I have been having "no response" issues when I am not in home LAN. That is sometimes, not always. With VPN connection to my home LAN the issue disappears. I am wondering if this might be connected to Unifi setup somehow.
I tried to find how to install 1.3 beta through UI but failed to see the option anywhere.
Running 1.1.6 on Ubuntu 20.10 server on old 2008 MacBook Pro.

**Comment by chrispi68** [comment]
I have two Homebridge instances running on Ubuntu on two seperated HyperV VMs. I also got the "No response" problem. "No response" is shown on devices from both Homebridge instances. Restating one instance fixes the problem for both instances. Native HomeKit devices, which are not provided by Homebridge, are not effected by this problem.

**Comment by Supereg** [comment]
@composerkaumann when running a somewhat recent version of homebridge ui you can do it like shown in the animation:
![change-homebridge-version](https://user-images.githubusercontent.com/3979615/96521915-15936700-12be-11eb-9826-f19b201d20db.gif)

@chrispi68 what version of homebridge are you running?

**Comment by chrispi68** [comment]
I am running v1.2.3 on both instances. I did not try out the beta.

**Comment by FSTNDonald** [comment]
@supereg - installed the beta ytd evening. Had the iphone since that on LTE only -> alltime HK connectivity established to the HB devices over a period of 24 h.
Looks fine for now - kudos to you / the team ;-))

PS: "no response" happened for 1.1.6 and for 1.2.3 versions. I enable IPv6 even for the beta, causing no issues.

cheers

**Comment by composerkaumann** [comment]
I have a quick question:
First- installed latest beta. All HB accessories went to "no response" state in Homekit, in HB web interface they were working still.
I got freaked out because I have around 100 different conditional automations and corresponding scenes. Reverted to 1.1.6 and stuff works again.
Why did this happen and can I get beta running with my automations still intact?

**Comment by FSTNDonald** [comment]
@composerkaumann - HK "no response" -> all ATVs / iPODs / iPhones discarded connections to the HB server. Proof: login HB, open 'terminal' and issue (or put into loop) command "netstat -ano | grep yyyyyy", whereas yyyyyy replaced by 'port' of HB config.
Refering my screenshot couple of posts above: whenever connection is 'ESTABLISHED' to ATV / iPOD / iPhone, all is fine. Status "LISTEN" reveals missing connectivity, i.e. "no response" on HK.
Check next: disable WLAN on iPhone, thus connect to your home via iCloud linked to ATVs / iPODS across your router.
Same procedure 'netstat' ... are connections established between ATVs / iPODS ?
Part of my problem was related to SUNXI kernal not handling IPv6 connections properly. Its worth trying disabling IPv6 on your platform, result ?

**Comment by composerkaumann** [comment]
Tried 1.3 beta again. Endless log pollution and the result is "not running"
Example:
2020-12-04T22:29:58.570Z ciao:Responder Sending response via multicast on network ens5 (took 4 ms): [PTR,PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC,TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 617B (UPS: 1440) 
2020-12-04T22:29:59.398Z ciao:Responder Sending (delayed 117ms) response via multicast on network interface ens5 (took 2 ms): [PTR,PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC,TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 617B 
2020-12-04T22:30:33.068Z ciao:Responder Sending response via multicast on network ens5 (took 6 ms): [PTR,PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC,TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 617B (UPS: 1440) 
[12/5/2020, 12:30:47 AM] [Hallway lights off] Time is Up! 
2020-12-04T22:30:59.654Z ciao:Responder Sending (delayed 25ms) response via multicast on network interface ens5 (took 2 ms): [PTR,PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC,TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 617B 
2020-12-04T22:31:03.912Z ciao:Responder Sending response via multicast on network ens5 (took 5 ms): [PTR,PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC,TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 617B (UPS: 1440) 
2020-12-04T22:31:38.208Z ciao:Responder Sending response via multicast on network ens5 (took 5 ms): [PTR,PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC,TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 617B (UPS: 1440)

**Comment by chrispi68** [comment]
> I am running v1.2.3 on both instances. I did not try out the beta.

I tried 1.3.0 Beta for 2 days and the problem disappeared.

**Comment by composerkaumann** [comment]
Tried 1.3.0 beta 31- around 2/3 of all accessories had "no response" state.

Did not get ciao errors in logs any more though.

Now on 1.2.4 and so far so good.

**Comment by Supereg** [comment]
> Tried 1.3.0 beta 31- around 2/3 of all accessories had "no response" state.

@composerkaumann could you elaborate if there is a "pattern" on which accessories work and don't work with the beta? Could it be that it may be an issue with some of the plugins? Would be great to get an overview over your setup.
In contrast to 1.3.0 beta, the 1.2.4 release works for you?

**Comment by Supereg** [comment]
@MichaelMrak as you are the original author of this thread, would be great to hear back from you. Does installing the homebridge 1.3.0 beta work for you? Or could you already boil it down to a bugged plugin?

**Comment by composerkaumann** [comment]
> > Tried 1.3.0 beta 31- around 2/3 of all accessories had "no response" state.
> @composerkaumann could you elaborate if there is a "pattern" on which accessories work and don't work with the beta? Could it be that it may be an issue with some of the plugins? Would be great to get an overview over your setup.
> In contrast to 1.3.0 beta, the 1.2.4 release works for you?

My setup is HB running on Ubuntu Server 20.10 on 2008 MacBook Pro (no MacOS installed). Main acessories are handled by Homebridge Ewelink, Homebridge Broadlink Rm Pro, Homebridge Milight and Homebridge ZP plugins. I have Apple TV HD as a main Homekit hub and few iPads as backups, all running 14.2.
Yes, 1.2.4 works for me. In 1.3.0 beta 31- all accessories work from HB web interface but none work with Homekit. I have IPv6 switched off on HB server and Netstat shows this:
`music@mbpubu:~$ netstat -ano | grep 52799
tcp        0      0 127.0.0.1:38070         127.0.0.1:52799         TIME_WAIT   timewait (21.45/0/0)
tcp        0      0 127.0.0.1:38062         127.0.0.1:52799         TIME_WAIT   timewait (1.45/0/0)
tcp6       0      0 :::52799                :::*                    LISTEN      off (0.00/0/0)
tcp6       0      0 127.0.0.1:52799         127.0.0.1:38066         TIME_WAIT   timewait (11.45/0/0)
tcp6       0      0 10.1.1.55:52799         10.1.1.128:62958        ESTABLISHED off (0.00/0/0)
tcp6       0      0 10.1.1.55:52799         10.1.1.77:49191         ESTABLISHED off (0.00/0/0)
tcp6       0      0 10.1.1.55:52799         10.1.1.91:62075         ESTABLISHED off (0.00/0/0)
tcp6       0      0 127.0.0.1:52799         127.0.0.1:38082         TIME_WAIT   timewait (51.45/0/0)
tcp6       0      0 10.1.1.55:52799         10.1.1.135:49212        ESTABLISHED off (0.00/0/0)
tcp6       0      0 10.1.1.55:52799         10.1.1.71:49509         ESTABLISHED off (0.00/0/0)
tcp6       0      0 127.0.0.1:52799         127.0.0.1:38078         TIME_WAIT   timewait (41.45/0/0)
tcp6       0      0 127.0.0.1:52799         127.0.0.1:38074         TIME_WAIT   timewait (31.45/0/0)
tcp6       0      0 10.1.1.55:52799         10.1.1.137:51345        ESTABLISHED off (0.00/0/0)`

**Comment by MichaelMrak** [comment]
> @MichaelMrak as you are the original author of this thread, would be great to hear back from you. Does installing the homebridge 1.3.0 beta work for you? Or could you already boil it down to a bugged plugin?

I installed Homebridge on an old Mac Mini and it works fine there. So I am currently not able to verify on Raspberry. Sorry.

**Comment by sep77** [comment]
all running14.02.iphone 7 is ok.iphone 11 and 12 "no response" state.
