### ISSUE TITLE
Homebridge won't connect to Home

### ISSUE THREAD

**Issue by joeblack2k** [homebridge/homebridge#2754]
Hello,

normally i figure out my own problems but this time i can't tackle it. When i try to add Homebridge to Home it hangs on "Connecting to Bridge" i have been running Homebridge for years but suddenly this pops up. 

i've tried: 
- creating a new docker
- delete the config folder (renamed it) and made a new /volume1/docker/homebridge folder
- put the docker on macvlan and let it host on its own ip
- checked the settings on my Ubiquiti Dream Machine and made sure mdns was enabled
- enabled debug logs but there is no message that it's trying to connect to anything

it's all running on a Synology DS920+ in a Docker latest version of everything.

if anyone has any idea i would love to try it.

greetings and thanks for reading

**Comment by Quiqui64** [comment]
I’ve had the same problem recently, not sure how I fixed it.
Try rebooting your home hub I.e. “Apple TV”. Wait for a little while. If that doesn’t work logout of your iCloud account and log back in.

**Comment by ambanmba** [comment]
Same here... tried rebuilding/rebooting/uninstalling/reinstalling/signing out/signing in... nothing. The setup was working wonderfully stably for ages and just stopped from one day to the next without any obvious changes.

**Comment by Miesvanderlippe** [comment]
I'm using the Pi image and it's having the exact same (mis-) behavior. First accesories stopped responding and I too have deleted the bridge from Home and can't add it back. 

What I've tried: 
- Remove all automation
- Remove newly added accessories
- Remove previously slow (but non problematic) humidity & temp sensor
- Reboot, update, restart the entire Pi, disconnect the Pi from the network, check all IP settings
- Checked if any part of the network uses IPV6 (because I read it doesn't work) 
- Remove bridge from Home

**Comment by marconr9** [comment]
Maybe try change to change the username in the configuration it looks like a MAC address. I had the samen problem
