### ISSUE TITLE
Siri of Apple HomePod told me that a part of devices ware no response.

### ISSUE THREAD

**Issue by anatsuk1** [homebridge/homebridge#2782]
**Describe The Bug:**

Siri of Apple HomePod told me that a part of devices ware no response.
Actually Siri speaks "一部のデバイスが応答しませんでした" in Japanese so I translated What Siri said.

**To Reproduce:**

Say "Hey Siri. Set [scene name]"
I translated my request into English for your convenience.

**Expected behavior:**

Siri of Apple HomePod says success or same mean sentence.
My home moves to [scene name] that I requested.

[**Logs:**]()

Homebridge launched with D option output the followings to journal log at the time of this issue occurring.
```
Jan 24 23:20:27 raspberrypi homebridge[467]: 2021-01-24T14:20:27.511Z HAP-NodeJS:EventedHTTPServer [xxxx::xxxx:xxxx:xxxx:9958%wlan0] Client connection closed
Jan 24 23:20:27 raspberrypi homebridge[467]: 2021-01-24T14:20:27.518Z HAP-NodeJS:EventedHTTPServer [xxxx::xxxx:xxxx:xxxx:9958%wlan0] HTTP connection was closed
Jan 24 23:20:27 raspberrypi homebridge[467]: 2021-01-24T14:20:27.519Z HAP-NodeJS:EventedHTTPServer [xxxx::xxxx:xxxx:xxxx:9958%wlan0] HTTP server was closed
```

**Homebridge Config:**

You can see my config.json here:
https://github.com/anatsuk1/cmd4_adrsir/blob/main/config.json

**Screenshots:**

No screenshot.

**Environment:**

* **Node.js Version**: v12.20.1
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.2.5
* **Operating System**: Raspberry Pi OS
* **Process Supervisor**: Systemd

**Comment by mrmaximas** [comment]
same shit

**Comment by vincer** [comment]
Yes, same here. I have 3 HomePods (2 regulars in a stereo config and 1 mini) and they all have the same issue where it will say something akin to "device isn't responding." I've only seen this on the HomePods. I can use my iPhone, iPad and Mac all without issue. Seconds after the HomePod says "not responding" I can use my iPhone and it will work no problem, and then, just to check I will immediately try the HomePod again and she still says "not responding" there. Unfortunately it's also an intermittent issue. A lot of the time it works fine.

I checked my wifi. iPhone and HomePod are all on the same 5GHz network (Unifi), homebridge is on a linux box that is using ethernet. Wifi connections to the Homepods are strong (866 Mbps).

I *think* I found a "fix" though which is to upgrade to the 1.3 beta. I'm guessing this has something to do with the ciao mdns library used in 1.2. Though my network is relatively ho-hum, no multiple VLANs or anything else that people have mentioned having issues mdns issues with ciao. See the "mDNS Advertiser Library" section in #2765 .

In any case, I've been using 1.3 for a few days now and no issues since then, though I'll update here if the issue reappears.

@anatsuk1 @mrmaximas -- Try upgrading to the 1.3 beta (or downgrade to 1.1.x).

**Comment by anatsuk1** [comment]
Hi @vincer,
Thanks for your advice.
I will update Homebridge to 1.3 beta.

I confirmed the section in #2765 that Homebridge version 1.3 beta was changed to use by default bonjour-hap, previous mDNS, instead of ciao.
I hope ciao will be stable soon.

**Comment by oznu** [comment]
Closing as @anatsuk1 has a solution. Homebridge 1.3 will address this by allowing users to select which mDNS library works best for them.

**Comment by sieren** [comment]
Confirming this affected me as well. Seen on HomePod Mini Devices only, works fine when using iOS Home App. Restarting Homebridge fixed it - switched back to mDNS Bonjour for now.

**Comment by wroblewski6** [comment]
i have the same problem on HomePod but nothing helps
