### ISSUE TITLE
Node.js v14.15.5 update caused failure

### ISSUE THREAD

**Issue by pjbarnett** [homebridge/homebridge#2810]
I have an installation working fine with over a dozen plugins.

It was working fine this morning on Node.js v14.15.4 and NPM v6.14.11.

A couple of my plugins are showing updates and in the notes is states they are for Node.js v14.15.5. So I followed the instructions and upgraded the Node. After this and prior to updating plugins, the Homebridge would start, error with conflicting UUID and a couple of red lines of text and then shutdown and cycle again. I initially thought it might be the plugins with updates however this didnt solve the issue. I then updated homebridge from v1.2.5 to the new beta which allowed me to disable plugins. I finally managed to get it working by pretty much disabling all the plugins! 

Is this normal and something to do with 14.5.5? Luckily I had a backup and by doing a restore I've managed to get up and running again. I also selected to install node 14.15.4 again by running sudo hb-service update-node 14.15.4 however it still shows I am on 14.15.5 so I am not sure if that worked successfully.

I also see there is a NPM version higher. Should I update this?

Hope this is in the right place as its general homebridge rather than a particular plugin. Apologies if it should be elsewhere.

**Comment by oznu** [comment]
> After this and prior to updating plugins, the Homebridge would start, error with conflicting UUID and a couple of red lines of text and then shutdown and cycle again. 

This is unrelated to the node version update and is caused by a plugins incorrect handling of cached accessories, or two accessory-type plugins defined with the same name.

You probably could have resolved the issue by removing the offending cached accessory from the Homebridge Settings section of the UI.

> however it still shows I am on 14.15.5 so I am not sure if that worked successfully

The nodesource repos only provide the latest version of the release (I.e. latest 14.x) - so this is what gets installed.
