### ISSUE TITLE
Some accessories (always the same) in "no response" mode when I'm away from home

### ISSUE THREAD

**Issue by vzlgdu** [homebridge/homebridge#2940]
Hi, starting from some weeks ago, I've a strange problem with my HB setup:
I use HB on RPI3 and many accessories with mqttthings plugin and some others with shelly plugin.
At home I've Apple TV 4 that manage all when I'm away.
When I'm at home all works fine.

When I'm away from home, more or less after 1 hour, 12 accessories (always the same) go in "no response"; many of this are from mqttthings (but others works fine) and some from shelly (but others works fine).

If I come back home all works fine again.
If I'm away ant this situation happens, If I restart HB from remote the problem is solved.

I've already reset ATV but the situation is the same.

Any ideas?

Thanks

**Comment by newbiech** [comment]
Same for me. 

RPI4, hardwired. Additionally installed a Pi-Hole and deconz-GW for the RaspbeeII on it. While in the same network at home all is fine. Once I move my cellphone to the mobile network the home app loses connection to the devices from time to time. After a while, all is back on line. I have no mqtthings things. Important to note: The ATV remains responsive but no non-HK devices. Not one. Already signed the ATV off from iCloud. Deleted the Homebridge from HomeKit and re-added it. Did not work.

To note:
ATV on official most recent FW. iPhone 12 Pro on iOS beta 14.7. However, my wife with an iPhone 12 Pro with most recent official iOS is working neither.

I have no clue how to trace down this issue. Any ideas?

**Comment by 9vska** [comment]
Not sure if this helps, but try child-bridging your installed plug-ins and see if that helps.

I had the same issues with a Pi Zero. Recently migrated to a Pi 4 and the problem persisted. Thought it had to do with using HomeKit via a VPN (because the devices were okay after I was on my LAN), but some new problems popped up in the form of unresponsive devices when I’m not actioning them directly through the Home app.

I’ve been testing the new set-up for the past several days. Besides an issue where the Pi 4 went offline due to some networking issues, the “no response” message hasn’t reared its ugly head (touchwood!)

**Comment by newbiech** [comment]
I decided to reinstall. D/L of the image from homebridge.io and going through all necessary steps. No fast setup, as I need to get homebridge-knx and KNXD working for all my KNX devices. In the end I am utilizing the same configs from the previous installation. No other changes but a fresh install.

You know what? It works flawlessly.

So it had nothing to do with configs (using the old ones on the new), nothing with the Raspi itself (I have two here for testing), nothing with the ATV (still the same) and nothing with the iOS beta on my iPhone. Unfortunetly, the previous installation did not expose any errors in the logs. Therefore, there is no way to trace the issue down.

**Comment by valeriansaliou** [comment]
Hey there, had the same issue after moving from Bonjour HAP to Ciao. Worked flawlessly when at home, but then moved away from home and noticed all accessories with Homebridge as their bridge showed as "No Response".

Connected back to my home network using a VPN, moved Homebridge back to Bonjour HAP, and things went back to normal.

I moved to Ciao since Bonjour HAP was periodically flooding my LAN with unsolicited mDNS answers, which successfully fixed the flood. However, it looks like this broke remote access to my home accessories.

I have a pretty simple network topology though, no LAN packet filtering, everything on the same LAN, very few equipments, thus I was surprised this did not work as it seemed that Ciao current limitations didn't apply to me.

As I have a dual-stack IPv4 and IPv6 network, this is probably linked to that: https://github.com/homebridge/ciao/issues/10 (but unsure as it states this happens in an IPv6-only environment — but maybe IPv6 interferes there?).

**Comment by vzlgdu** [comment]
Sorry, so what protocol seems solve the problem? Bonjour or ciao?


Guido Vizioli

**Comment by valeriansaliou** [comment]
Switching back to Bonjour HAP solved the problem for the non-working remote access. Then I switched back to Ciao from there and services were marked as responding again (and they still are responding under Ciao). That's weird, I'll post an update if this happens again w/ Ciao.

I've seen some people reporting similar issues on Reddit after switching to Ciao, which auto-solved themselves after 24-48h of waiting and doing nothing, probably some caching issue involved?
