### ISSUE TITLE
Problem remembering Config.json settings

### ISSUE THREAD

**Issue by Damianod27** [homebridge/homebridge#2997]
Hello.

First of all, sorry for my English. I have two Homebridge bridges.
The first one in the house based on the Raspberry Pi 4 and everything works fine here.
The second one at Job is based on Orange Pi Zero. It runs on Debian Buster 10.
All systems are updated to the newest (Debian, Node.js, Homebridge). The problem is
that when I install the plug and configure it. Then I will click on RESTART to have the plugin loaded with the configuration.
Up to this point, everything is fine. When I turn off the power to the Bridge, no matter if after an hour or two, it turns out that
after restarting Homebridge, the CONFIG.JSON file does not save any settings from the plugin installed. The situation looks like
otherwise, when after installing the plugin and its configuration, instead of using RESTART it will use RESTART SERVER. Then the plugin configuration in the CONFIG.JSON file is remembered. I can disconnect the bridge from the power supply and after restarting everything works fine. I added the homebridge user to the group Sudo but it doesn't do anything.
I don't understand why I can't use the RESTART function which is much faster than the RESTART SERVER.

Can someone please help me?

Best Regards 
Damian

System Information : 
OS : Debian GNU/Linux Buster (10)
Hostname : homebridge
Node.js Version : 14.18.1
NPM Version : 6.14.15
User : homebridge
Storage Path : /var/lib/homebridge
Config Path : /var/lib/homebridge/config.json
Service Mode | Yes
Homebridge Version : 1.3.5
Homebridge UI : 4.41.2
![System INFO  Homebridge](https://user-images.githubusercontent.com/79320859/137999501-48d3d0e7-f4fb-4779-940c-e206274bed50.png)

**Comment by hertugweile** [comment]
I have a similar issue, I believe... all my paired sensors are missing after a reboot. On re-pairing, it returns errors, since the sensors apparently hasn't been unpaired, but they reappear, anyway.

I use Homebridge Zigbee Nt and Homebridge Zigbee2mqtt

Here are some screendumps to illustrate: 
http://vandret.dk/support/1sensors_added.jpg (added two sensors, an Aqara temp/humidity and a Aqara leak sensor)
http://vandret.dk/support/2sensors.jpg (seems, they already exist from last time, they were paired?)
http://vandret.dk/support/3restarted.jpg (after a soft restart, they still appear)
http://vandret.dk/support/4hardrestart.jpg (Restart of the Raspberry Pi)
http://vandret.dk/support/5afterrestart.jpg (After restart, the sensors are gone)
http://vandret.dk/support/6accessories.jpg (Same in the accessories tab. Waiting several (10) minutes makes no difference)
