### ISSUE TITLE
Since 1.4.0 little bug with cache i think

### ISSUE THREAD

**Issue by fennec622** [homebridge/homebridge#3073]
### Analysis

Since 1.4.0 when i switch a light or outlet in on mode or off mode

### Expected Behavior

Mqtthing object 

I change state and immediatly come back in original state but in reality command is ok, i close home and i restart and the state is the good state 

In 1.3.9 all is ok 
it's Mqtthing object 

https://user-images.githubusercontent.com/24509422/150740382-45fbed67-7ee3-4479-b11b-2033df09f2aa.MP4

### Steps To Reproduce

Just change state 
the second change is ok statut 

### Logs

```markdown
[24/01/2022, 08:38:02] [Escalier] Publishing MQTT: zigbee2mqtt/boutonentree2/right/set = ON
[24/01/2022, 08:38:04] [Escalier] Received MQTT: zigbee2mqtt/boutonentree2 = {"action":null,"last_seen":"2022-01-24T07:38:04.730Z","linkquality":61,"operation_mode_left":null,"operation_mode_right":null,"state_left":"OFF","state_right":"OFF"}
[24/01/2022, 08:38:04] [Escalier] apply() function decoded message to [OFF]
[24/01/2022, 08:38:04] [Escalier] Received MQTT: zigbee2mqtt/boutonentree2 = {"action":null,"last_seen":"2022-01-24T07:38:04.730Z","linkquality":61,"operation_mode_left":null,"operation_mode_right":null,"state_left":"OFF","state_right":"ON"}
[24/01/2022, 08:38:04] [Escalier] apply() function decoded message to [ON]
[24/01/2022, 08:38:04] [Escalier] Received MQTT: zigbee2mqtt/boutonentree2 = {"action":null,"last_seen":"2022-01-24T07:38:04.861Z","linkquality":61,"operation_mode_left":null,"operation_mode_right":null,"state_left":"OFF","state_right":"ON"}
[24/01/2022, 08:38:04] [Escalier] apply() function decoded message to [ON]
```

### Configuration

```json
{
            "accessory": "mqttthing",
            "type": "lightbulb",
            "name": "Escalier",
            "topics": {
                "getOn": {
                    "topic": "zigbee2mqtt/boutonentree2",
                    "apply": "return JSON.parse(message).state_right"
                },
                "setOn": "zigbee2mqtt/boutonentree2/right/set",
                "getOnline": {
                    "topic": "zigbee2mqtt/boutonentree2/availability",
                    "apply": "return message == 'online' ? 'ON' : 'OFF';"
                }
            },
            "logMqtt": false,
            "integerValue": false,
            "onValue": "ON",
            "offValue": "OFF",
            "turnOffAfterms": "120000",
            "onlineValue": "ON",
            "offlineValue": "OFF"
        },
```

### Environment

- OS: RPY last 
- Software: 1.4.0
- Node:16.13.1
- npm:8.1.2

### Process Supervisor

hb-service

**Comment by dmertsalov** [comment]
I have the same problem, only the status returns to the previous one (already erroneous) a little faster than in the video. Helps to close/open the application. There are other devices added via Node-RED, and they don't have such status issues.

**Comment by NorthernMan54** [comment]
@dmertsalov @fennec622 This appears to be an issue with the mqttthing plugin, and shouldn't this issue be raised there, rather than here where the mqttthing plugin developer may never see it ?

**Comment by fennec622** [comment]
> @dmertsalov @fennec622 This appears to be an issue with the mqttthing plugin, and shouldn't this issue be raised there, rather than here where the mqttthing plugin developer may never see it ?

Yes I post on mqtthing thanks

**Comment by satter** [comment]
I do not have mqttthing, but I have homebridge-z2b in my setup, still I have same problem with accessory state.

In my case it all started with simultaneous upgrade of z2m (1.22.2 -> 1.23.0) and hb (v1.3.9 -> v1.4.0), but homebridge-z2m version has not changed (1.6.2)

[Here](https://github.com/itavero/homebridge-z2m/issues/383) is the same issue in hb-z2m project, I think
I could not find anything related in z2m issues

**Comment by itavero** [comment]
@fennec622 Can you perhaps link the issue you created for mqtthing?

**Comment by fennec622** [comment]
> @fennec622 Can you perhaps link the issue you created for mqtthing?

No answer ...
https://github.com/arachnetech/homebridge-mqttthing/issues/533

**Comment by itavero** [comment]
As mentioned in [this comment](https://github.com/itavero/homebridge-z2m/issues/383#issuecomment-1067744295) on itavero/homebridge-z2m#383, it seems to be related to `hap-nodejs` being upgraded to 0.10.0

A user reports that downgrading `hap-nodejs` to 0.9.8, resolves the issue for him.

**Comment by NorthernMan54** [comment]
I just tried to recreate this issue, with my homebridge-tasmota plugin, based on the use case documented here https://github.com/itavero/homebridge-z2m/issues/383 and was not successful.

If you enable HAPNode-JS debug logging it gives more detail into the communications between the Home app and Homebridge

ie start Homebridge from the command line like this

```
DEBUG=HAP-NodeJS:* homebridge
```

And the logs look like this ( this is turning off my Patio Room light from the Home App ).  For the test I had the Home app open to the Patio Room on 2 separate devices, iPhone and Mac Desktop so I could watch the updates.

```
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.88] HTTP request: /characteristics +5s
  HAP-NodeJS:HAPServer [AB:BB:CC:DD:EE:01] HAP Request: PUT /characteristics +6s
  HAP-NodeJS:Accessory [Pinkman 3AB1] Processing characteristic set: {"characteristics":[{"aid":2,"iid":10,"value":0}]} +6s
[Tasmota] Patio Room Set Characteristic On -> false
  Tasmota:mqtt sendMessage cmnd/tasmota_0B62D5/POWER OFF +5s
  HAP-NodeJS:EventedHTTPServer [::ffff:192.168.1.88] Muting event '2.10' notification for this connection since it originated here. +6s
  HAP-NodeJS:Accessory [Pinkman 3AB1] Setting Characteristic "On" to value 0 +0ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.88] HTTP Response is finished +0ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.93] Sending HAP event notifications [ { aid: 2, iid: 10, value: 0 } ] +251ms

  Tasmota:mqtt emit tele/tasmota_0B62D5/STATE {"Time":"2022-03-15T14:04:37","Uptime":"43T00:44:52","UptimeSec":3717892,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":34,"MqttCount":17,"POWER":"OFF","Dimmer":52,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"The_Beach","BSSId":"90:72:40:18:A7:BE","Channel":1,"Mode":"11n","RSSI":94,"Signal":-53,"LinkCount":11,"Downtime":"0T00:00:55"}} +381ms
  Tasmota:light statusUpdate tele/tasmota_0B62D5/STATE {"Time":"2022-03-15T14:04:37","Uptime":"43T00:44:52","UptimeSec":3717892,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":34,"MqttCount":17,"POWER":"OFF","Dimmer":52,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"The_Beach","BSSId":"90:72:40:18:A7:BE","Channel":1,"Mode":"11n","RSSI":94,"Signal":-53,"LinkCount":11,"Downtime":"0T00:00:55"}} +6s
[Tasmota] Updating 'Patio Room' to OFF
[Tasmota] Updating 'Patio Room' Brightness to 52
  Tasmota:light statusUpdate tele/tasmota_0B62D5/STATE {"Time":"2022-03-15T14:04:37","Uptime":"43T00:44:52","UptimeSec":3717892,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":34,"MqttCount":17,"POWER":"OFF","Dimmer":52,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"The_Beach","BSSId":"90:72:40:18:A7:BE","Channel":1,"Mode":"11n","RSSI":94,"Signal":-53,"LinkCount":11,"Downtime":"0T00:00:55"}} +1ms
[Tasmota] Updating 'Patio Room' to OFF
[Tasmota] Updating 'Patio Room' Brightness to 52
```

Of interest is this message here, which is telling the other instance of the Home app to change the status of the Patio Room light to Off

```
AP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.93] Sending HAP event notifications [ { aid: 2, iid: 10, value: 0 } ] +251ms
```

My theory on your issue is the handling of status updates from the device to Homebridge and HomeKit, are possibly sending an incomplete or old value to Homebridge ?  This would be evident in the above log with an additional event notification with the incorrect status

PS In the log it starts with the characteristic set command coming in from the Home App, then an event notification to the other instance of the home App.  Then the status update message comes in from the Tasmota device, and is processed by the plugin.   As the device status does not change, their is no event notification.

**Comment by itavero** [comment]
[Logging provided](https://github.com/itavero/homebridge-z2m/issues/383#issuecomment-1068084461) in itavero/homebridge-z2m#383, for v0.10.0:

```
2022-03-15T14:50:47.052Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.5.24] HTTP request: /characteristics
2022-03-15T14:50:47.052Z HAP-NodeJS:HAPServer [0E:5F:CE:A3:AA:E9] HAP Request: PUT /characteristics
2022-03-15T14:50:47.053Z HAP-NodeJS:Accessory [Homebridge AAE9 EBC0] Processing characteristic set: {"characteristics":[{"aid":112,"iid":11,"value":0}]}
2022-03-15T14:50:47.054Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.5.24] Muting event '112.11' notification for this connection since it originated here.
[3/15/2022, 2:50:47 PM] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x680ae2fffe598667/set': '{"state":"OFF"}'
2022-03-15T14:50:47.058Z HAP-NodeJS:Accessory [Homebridge AAE9 EBC0] Setting Characteristic "On" to value 0
2022-03-15T14:50:47.060Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.5.24] HTTP Response is finished
2022-03-15T14:50:47.433Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.5.24] Sending HAP event notifications [ { aid: 112, iid: 11, value: 1 }, { aid: 112, iid: 11, value: 0 } ]
```

Compared to the logs of v0.9.8, the thing that stands out is that there our two event notifications rather than a single one.
User did indicate that with the debug logs turned on, it was harder to reproduce the behavior.

**Comment by NorthernMan54** [comment]
This is odd `2022-03-15T14:50:47.433Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.5.24] Sending HAP event notifications [ { aid: 112, iid: 11, value: 1 }, { aid: 112, iid: 11, value: 0 } ]`

Turning On then Off in the same event notification

Can you point out the 'set' event handler in the [homebridge-z2m](https://github.com/itavero/homebridge-z2m) code base ?

Also does the plugin receive real time status updates from the device ?  In my log fragment these show up after the 'set' event is handled.

**Comment by itavero** [comment]
> Can you point out the 'set' event handler in the [homebridge-z2m](https://github.com/itavero/homebridge-z2m) code base ?

People are reporting this for different device types (which are spread across several sources). These handlers are all pretty similar though (they queue data to be published to MQTT later on).
The implementation for a smart socket/switch can be found [here](https://github.com/itavero/homebridge-z2m/blob/v1.7.0/src/converters/switch.ts#L71-L76).

> Also does the plugin receive real time status updates from the device?

Yes, it receives updates via MQTT. It seems that Zigbee2MQTT (the system being integrated by this plugin) might sometimes publish the previous state before publishing the new one (based on the logs people have shared in the aforementioned issue).
What I find interesting is that this does not seem to lead to any problems on v0.9.8 of HAP-NodeJS, but does result in this behavior with v0.10.0 (provided the same/similar input over MQTT).

**Comment by NorthernMan54** [comment]
If the HAP Event notification that sends an On / Off at the same time is seen all cases when the issue occurs we have something to work with. This `Sending HAP event notifications [ { aid: 112, iid: 11, value: 1 }, { aid: 112, iid: 11, value: 0 } ]` condition.

I did go back and look at the history of that event notification framework within HAPNode-js and found that @Supereg had made an improvement to the event notification framework https://github.com/homebridge/HAP-NodeJS/pull/925 that may explain why the issue is not apparent with v0.9.8.

Reading the notes from @Supereg it appears that the old version of the code would have suppressed the two messages into a single message, and only passed along the lastest one.  Which might explain why it was okay with the old version, but not with the new.  This could be a latent issue with the plugin design, that was only exposed with this change.

Question is the plugin sending two state update notifications at the same time interval to HAPNode-JS or is HAPNode-JS for some reason sending a stale value ?  To figure this out further, I looked at the logging within HAPNode-JS, and state ( get, set or updateValue ) updates from a plugin are not debug logged today so I was thinking some additional logging is needed to gain visibility into the plugin interface.

If I was able to recreate the issue, I would go into distributed version of HAPNode-JS and add some console logging to homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js to gain visibility into the HAPNode-JS / Plugin interface.  Or the reverse on the plugin side.  And the Characteristic CharacteristicEventTypes event emitter https://github.com/homebridge/HAP-NodeJS/blob/178bd7a6d707d258109be932f2e0055f9a3048f6/src/lib/Characteristic.ts#L453

**Comment by alexwala** [comment]
any news on this subject ?
having same issue using homebridge-z2m

**Comment by itavero** [comment]
> any news on this subject ?

Not from my side. I see I forgot to ask @lyonanderson if he would be able to add the logging suggested above.

One thing I did think of: I use `process.nextTick` to delay publishing the data to MQTT. If I remember correctly, I did this so that all actions from HomeKit would more or less be bundled in a single message.
Perhaps I need something similar for the data coming in from MQTT (not sure if `nextTick` is the interval you are referring to, @NorthernMan54 ?).

**Comment by fennec622** [comment]
> any news on this subject ? having same issue using homebridge-z2m

No

For me if i wan't to fix this bug i must disable cache_state on zigbee2mqtt for have just one command return

**Comment by NorthernMan54** [comment]
@itavero What is was referring to was changes coming into HAP-NodeJS fast enough to trigger the message queuing.  Which could be from the usage of `nextTick` but until we can dig deeper its all speculation.

**Comment by alexwala** [comment]
> For me if i wan't to fix this bug i must disable cache_state on zigbee2mqtt for have just one command return

yes, that actually seems to help

**Comment by itavero** [comment]
> @itavero What is was referring to was changes coming into HAP-NodeJS fast enough to trigger the message queuing.

I'm pretty sure two MQTT messages came in for the same accessory in a very short timespan from Zigbee2MQTT due to caching it can do.
I have some ideas to make sure that there is "enough time" between processing incoming MQTT messages for the same accessory within my plugin.
That should then prevent this behavior/glitch from occuring.

The only part I'm struggling with is what's "enough" time?
Is there some way to tell from the plugin if there are still events pending for a particular accessory and/or to get an "callback" when all events have been transmitted?

**Comment by fennec622** [comment]
On zigbee2mqtt i can fix with add option 
debounce = 1
Add Time to message
And after that all is ok
1.4.1 home bridge

**Comment by dylexrocks** [comment]
> On zigbee2mqtt i can fix with add option
> debounce = 1
> Add Time to message
> And after that all is ok
> 1.4.1 home bridge

I tried your suggested workaround and added a debounce to my lights, but it did not work for me. What exactly do you mean by   
> Add Time to message

**Comment by fennec622** [comment]
> > On zigbee2mqtt i can fix with add option
> > debounce = 1
> > Add Time to message
> > And after that all is ok
> > 1.4.1 home bridge
> 
> I tried your suggested workaround and added a debounce to my lights, but it did not work for me. What exactly do you mean by
> 
> > Add Time to message

Hi

try with two options

> debounce
Debounces messages of this device. When setting e.g. debounce: 1 and a message from a device is received, Zigbee2MQTT will not immediately publish this message but combine it with other messages received in that same second of that device. This is handy for e.g. the WSDCGQ11LM which publishes humidity, temperature and pressure at the same time but as 3 different messages.

debounce_ignore
Protects unique payload values of specified payload properties from overriding within debounce time. When setting e.g. debounce: 1 and debounce_ignore: - action every payload with unique action value will be published. This is handy for e.g. the E1744 which publishes multiple messages in short time period after one turn and debounce option without debounce_ignore publishes only last payload with action rotate_stop. On the other hand debounce: 1 with debounce_ignore: - action will publish all unique action messages, at least two ( e.g. action: rotate_left and action: rotate_stop)

>

**Comment by dylexrocks** [comment]
> Hi
> 
> try with two options
> 
> > debounce
> > Debounces messages of this device. When setting e.g. debounce: 1 and a message from a device is received, Zigbee2MQTT will not immediately publish this message but combine it with other messages received in that same second of that device. This is handy for e.g. the WSDCGQ11LM which publishes humidity, temperature and pressure at the same time but as 3 different messages.
> 
> > debounce_ignore
> > Protects unique payload values of specified payload properties from overriding within debounce time. When setting e.g. debounce: 1 and debounce_ignore: - action every payload with unique action value will be published. This is handy for e.g. the E1744 which publishes multiple messages in short time period after one turn and debounce option without debounce_ignore publishes only last payload with action rotate_stop. On the other hand debounce: 1 with debounce_ignore: - action will publish all unique action messages, at least two ( e.g. action: rotate_left and action: rotate_stop)
> 
> debounce 2 group All same answer in 2s
> 
> debounce_ignore: - action For action payload

I finally had time to try out your suggestion. Unfortunately the behvavior did not change. I updated my homebridge to V1.5 and added the debounce setting to one of my bulbs. I still receive three messages when I turn on the bulb, just like I did without the debounce option. 
If I understand correctly what the `debounce ` parameter does, I think I don't need the `debounce_ignore` parameter, because I want exactly one message when I turn on the bulb, with all properties (e.g. state, brightness) having the latest value. So inside my configuration.yaml  I configured my bulb like this:
```
'0xec1bbdfffea31185':
    friendly_name: bulb/ct/arbeitszimmer-licht-decke
    retain: true
    qos: 2
    transition: 1
    debounce : 2
```
Then I went ahead and turned on my bulb using the zigbee2mqtt web ui. After that I receive three mqtt messages:
Message 1 15-08-2022 09:22:15.33735081
```
{
  "brightness" : 254,
  "color" : {
    "x" : 0.3804,
    "y" : 0.3767
  },
  "color_mode" : "color_temp",
  "color_temp" : 250,
  "last_seen" : "2022-08-15T09:22:15+02:00",
  "level_config" : {
    "on_level" : "previous"
  },
  "linkquality" : 178,
  "state" : "OFF",
  "update" : {
    "state" : "idle"
  },
  "update_available" : false
}
```
Message 2 15-08-2022 09:22:15.33735132
```
{
  "brightness" : 254,
  "color" : {
    "x" : 0.3804,
    "y" : 0.3767
  },
  "color_mode" : "color_temp",
  "color_temp" : 250,
  "last_seen" : "2022-08-15T09:22:15+02:00",
  "level_config" : {
    "on_level" : "previous"
  },
  "linkquality" : 178,
  "state" : "ON",
  "update" : {
    "state" : "idle"
  },
  "update_available" : false
}
```
Message 3 15-08-2022 09:33:16.33736971
```
{
  "brightness" : 254,
  "color" : {
    "x" : 0.3804,
    "y" : 0.3767
  },
  "color_mode" : "color_temp",
  "color_temp" : 250,
  "last_seen" : "2022-08-15T09:22:15+02:00",
  "level_config" : {
    "on_level" : "previous"
  },
  "linkquality" : 178,
  "state" : "ON",
  "update" : {
    "state" : "idle"
  },
  "update_available" : false
}
```
My advanced settings section looks like this:
```
advanced:
  pan_id: 8034
  cache_state: true
  log_level: info
  ikea_ota_use_test_url: false
  last_seen: ISO_8601_local
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  legacy_api: false
  cache_state_persistent: true
  cache_state_send_on_startup: false
  legacy_availability_payload: false
```
Do you have an idea why this is happening? Could you perhaps share your configuration so I could compare it to mine?
Thanks a lot in advance!

**Comment by JeanMertz** [comment]
It doesn't seem this issue is resolved yet, is it?

I keep visiting the issue from time to time, as I too experienced the described bug, and have since stuck to 1.3.9, as I don't want to risk breaking anything in Home.app, as that is instantly noticed by the rest in the family.
