### ISSUE TITLE
hb-service listening on port 5353 which conflicts with avahi daemon

### ISSUE THREAD

**Issue by seidnerj** [homebridge/homebridge#3077]
### Current Situation

I currently have homebridge running on a raspberry pi 4, historically the ".local" address for homebridge has not been consistent, presumably due to mDNS. To resolve this issue, I have been using Ciao for mDNS and disabled Avahi. When Homebridge 1.4.0 came out, I switched back to Avahi since Homebridge now supported it. 

Unfortunately the issue with homebridge's ".local" not being accessible has comeback. I started debugging this, the first thing I did was look at Avahi's log (by running sudo systemctl status avahi-daemon.service), which included the following sentence:
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***

Note that this is not always seen in the log since it depends on the order in which the various services listening on port 5353 are started, so after a "clean" restart this usually would not be visible but rather only upon restarting the avahi daemon.

I then proceeded to check which processes were listening on port 5353 (mDNS) and surprisingly discovered that there were 3:
1. avahi-daemon
2. chromium-browser
3. hb-service

I first disabled chromium-browser listening on this port by creating a policy file which disabled Chromium's media browser, this is done by creating a file named "disable_mediarouter.json"  at "/etc/chromium-browser/policies/managed" which contains the following JSON:
{ "EnableMediaRouter": false }

I then restarted the server and was indeed happy to discover that Chromium was no longer listening on port 5353. Unfortunately, the warning message still persists because hb-service is still listening on port 5353 in parallel to Avahi. I suspect the problem will persist as well, though I can't be sure for the time being. If not, then this can just be ignored obviously.

My question is why is hb-service listening on this port given it should be using Avahi as set in the configuration? is there a way to disable it from listening on this port? is this even a problem?

Thanks in advance

### Logs

```markdown
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-01-25 18:05:48 IST; 2s ago
 Main PID: 3579 (avahi-daemon)
   Status: "avahi-daemon 0.7 starting up."
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/avahi-daemon.service
           ├─3579 avahi-daemon: running [homebridge.local]
           └─3580 avahi-daemon: chroot helper

Jan 25 18:05:48 homebridge avahi-daemon[3579]: *** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***

pi@homebridge:~ $ sudo lsof -i:5353
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
hb-servic  882    pi   19u  IPv4  20089      0t0  UDP *:mdns 
avahi-dae 3579 avahi   12u  IPv4  40351      0t0  UDP *:mdns 
avahi-dae 3579 avahi   13u  IPv6  40352      0t0  UDP *:mdns
```

### Configuration

```json
N/A
```

### Environment

- OS: Rasperry Pi OS
- Software: Homebridge 1.4.0
- Node: v16.13.1
- npm: 8.3.0

### Process Supervisor

hb-service

**Comment by introns-bungles** [comment]
I have the exact same issue with Homebridge and Avahi.

### Logs

```
udp   UNCONN 0      0                                  0.0.0.0:5353       0.0.0.0:*    users:(("hb-service",pid=2145256,fd=19))
udp   UNCONN 0      0                                  0.0.0.0:5353       0.0.0.0:*    users:(("avahi-daemon",pid=2145048,fd=12))
```
### Environment

- OS: Arch Linux on x64
- Software: Homebridge 1.4.0
- Node: v16.13.2
- npm: 8.3.2

### Process Supervisor

- hb-service

**Comment by donavanbecker** [comment]
This should probably also be raise at homebridge-config-ui-c

**Comment by introns-bungles** [comment]
> This should probably also be raise at homebridge-config-ui-x, as that is what hb-service is built into.

Done.

**Comment by seidnerj** [comment]
I can now confirmed that after about a day or so, the ".local" address became inaccessible again. The obvious culprit is hb-service conflicting with Avahi but I cannot be 100% sure since I cannot disable hb-service (that's the entire point of this machine). 

Along with the .local address becoming inaccessible,  I also noticed that all the devices that were connected via homebridge became unresponsive. Since this happened around the same time (likely minutes apart) I think its safe to assume these are related.

**Comment by seidnerj** [comment]
I'm back to using Ciao, can't stand having to reset Avahi every 24 hours or so. Too bad.

**Comment by keremerkan** [comment]
Does your system report as using avahi in the first place? My Debian 11 system reverts to HAP even though I select ciao or avahi.

**Comment by seidnerj** [comment]
> Does your system report as using avahi in the first place? My Debian 11 system reverts to HAP even though I select ciao or avahi.

Yes, it does.

**Comment by keremerkan** [comment]
> Yes, it does.

Looks like I have bigger problems in addition to the 5353 conflict. I can't use any advertiser other than HAP.

**Comment by seidnerj** [comment]
Strange but likely not related to this exact issue.

**Comment by adriancable** [comment]
Hi everyone. I'm the author of the Avahi advertiser code in Homebridge.

There's at least four different things being talked about in this thread (which unfortunately makes it harder to track the conversation when some, or all of these things are referred to as "this exact issue").

1. hb-service seems to be listening on port 5353
2. avahi-daemon prints a warning on startup if something else is listening on port 5353 and/or there is a port 5353 "conflict" between multiple processes
3. some (which?) .local address becomes inaccessible after 24 hours
4. "can't use any advertiser other than HAP"

To each of those:

1. hb-service as I understand it is (amongst other things which don't have anything to do with publishing advertisements) a wrapper for Homebridge. If it's listening on port 5353 it means it is using the bonjour-hap or ciao advertiser. If you have set Homebridge to use the Avahi advertiser, then it means that either (1) you haven't set it correctly, or (2) you are running two copies of Homebridge at the same time without realising it. One you are changing the configuration of (e.g. to set Avahi as the advertiser), the other is running somewhere else and is using a standard/blank config file (and maybe no plug-ins at all) and therefore using the default advertiser, which is bonjour-hap. I have seen both of these, but my guess in your case @seidnerj is (2).
2. It is fine (almost always) for there to be multiple advertisers running on the system. They all use SO_REUSEADDR and it is totally fine for multiple processes to be listening to multicast traffic on the same UDP port. There is no port 5353 'conflict'.
3. avahi-daemon will usually advertise a whole bunch of things (like SSH, SFTP, etc.) which are not related to Homebridge. Please find these advertisements (using another machine on your network) and see if they go away when Homebridge stops working with Avahi selected as the advertiser. If they do, your problem has nothing to do with Homebridge and so you will have better results going through the normal mDNS troubleshooting steps that you can find all over the Web (e.g. mesh network with Ethernet devices connected to the satellites, router or managed switch with incorrect IGMP proxy/reflector settings, etc. etc.). I am guessing the reason why you haven't seen a lot of activity on this issue is that it isn't clear that your issue has anything to do with Homebridge at all. Please go through the steps to figure that out, and then post your results. A stronger case that your issue is actually Homebridge-related will give you stronger traction here.
4. Homebridge will use the advertiser you select - I promise @keremerkan ! If that appears not to be working, you are using an old version of Homebridge that doesn't support Avahi, or you are editing a different config file than the one Homebridge is picking up, or you are running the right config file but your edits are not being persistent (e.g. you're running stuff in Docker and each time you restart it's reverting to a clean state). If you want our help troubleshooting this, then please tell us exactly what you are doing, what versions of stuff you're running, what happens and when, tell us that you've verified that Homebridge is picking up the config file that you're editing, and in general, please, provide specifics on your own set-up and situation. You don't need to wait for someone else to ask for you to provide all these details - you can do that first and it'll dramatically short-cut the path to a solution. We are here to help you so I am sharing the reasons why maybe you haven't got much interest/traction on this thread from the Homebridge developers.

Hope this is helpful.

**Comment by keremerkan** [comment]
Hi @adriancable, thank you very much for your insight.

On my case, perhaps I had a misunderstanding when Homebridge says `Homebridge v1.4.0 (HAP v0.10.0) (Homebridge) is running on port xxxxx`.

`HAP v010.0` seems to be the one that uses avahi or ciao etc, am I correct? Because when I start Homebridge with the debug option, I see the following:

```
Publishing bridge accessory (name: Homebridge, publishInfo: {
  username: 'xx:xx:xx:xx:xx:xx',
  port: xxxxx,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'avahi'
}).
```

That shows `avahi`as the configured advertiser. If I remember correctly, earlier versions of Homebridge did start as `Homebridge v1.3.x (ciao)` hence my confusion, but it seems to be changed with the HAP plugin in some other earlier version. Currently, it looks like, to confirm the advertiser, our only option is the debug option.

So, point 4 on your reply seems to be resolved. Let's look at points 1 and 2, because we have some conflict there.

Currently, my Homebridge is set to `avahi` and we can be sure about that according to the logs. Also I have only one instance of Homebridge, I am also sure about that. My setup is on Debian, so I have complete shell control over the device unlike Docker etc.

You said and I quote "If it's listening on port 5353 it means it is using the bonjour-hap or ciao advertiser. If you have set Homebridge to use the Avahi advertiser, then it means that either (1) you haven't set it correctly, or (2) you are running two copies of Homebridge at the same time without realising it."

Here is the conflict. I have set Homebridge to `avahi` and there are no other instances. But hb-service is still listening to port `5353`:

```
$ sudo netstat -anp|grep 5353
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1011702/hb-service  
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           240668/avahi-daemon
```

I don't have a problem with .local addresses becoming inaccessible unlike @seidnerj, my only concern was `hb-service` still listening to port 5353, which could result in unwanted consequences. Seems like that will not be a problem. Still it may be beneficial to look at why it still listens to 5353.

**Comment by TimofeyK** [comment]
I have Homebridge installed with homebridge-config-ui-x (both latest versions). When using Avahi advertiser I also can see Homebridge listening on 5353 port but I experience absolutely **no issues**. Everything is stable, no warnings from Avahi

```
pi@plex:~ $ sudo netstat -anp|grep 5353
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           40346/homebridge    
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           397/avahi-daemon: r 
udp6       0      0 :::5353                 :::*                                397/avahi-daemon: r 
```

@seidnerj You seems to have some other issue, not related to Homebridge. Any chance you added "disallow-other-stacks= yes" in /etc/avahi/avahi-daemon.conf?

**Comment by seidnerj** [comment]
Hi all,
Thanks for all the input. 

@adriancable, thanks for the detailed response and kudos on starling home hub, I am a happy user myself. I have double check and I only a single instance of homebridge running. When Avahi is used I get a "homebridge.local" address which disappears after ~24 hours, I will check what happens to the other services it advertises. When running ciao for example, I get a slightly different .local address, something like "homebridge-6a7a-5276.local".

I understand that two services listening on the same UDP port should not be an issue, I just don't understand why this is happening and I thought this might be a clue. This happens also with a clean image of homebridge for Rasperry Pi.

@TimofeyK, I do not have "disallow-other-stacks=yes" set in a avahi configuration, in fact I do not have a line set for that at all, I only have a commented out like that say "disallow-other-stacks=no", I assumed the default is no but maybe that's not the case? not sure - I will check. Also, not that you would unlikely to the warning I mentioned if you have not restarted the avahi daemon after boot, since it is launched before hb-service and thus when launched it is in fact the only service listening on he aforementioned port and will show you the warning.

This is a very frustrating issue. I will continue digging into this when I have more time. For now, I am still back to using ciao and am still unclear as to why hb-service is litening on port 5353.

**Comment by seidnerj** [comment]
When using ciao and listing who is listening on port 5353 I can see the following:

```
pi@homebridge:~ $ sudo lsof -i:5353
COMMAND    PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
hb-servic  858   pi   19u  IPv4   19908      0t0  UDP *:mdns 
homebridg 7607   pi   27u  IPv4 1270667      0t0  UDP *:mdns 
homebridg 7607   pi   28u  IPv4 1270668      0t0  UDP *:mdns 
```

Interestingly, unlike Avahi, homebridge is not listening on IPv6 - maybe that is related to the issue I'm experiencing. It is also not clear to me why homebridge is listening to this port "twice".

**Comment by adriancable** [comment]
@seidnerj - I have not used homebridge-config-ui-x but I don't have any advance knowledge of what it should or shouldn't do. But I have just had a look at the source code (you can too! https://github.com/oznu/homebridge-config-ui-x) and it uses @oznu/hap-client to look for _hap._tcp instances on the network. Looking at github.com/oznu/hap-client you will see that it uses bonjour-hap, for the browser function (not the publisher). The browser also needs to listen to port 5353, because that's where responses come back to when it sends out probes.

So, hb-service listening on 5353 is normal and expected and by design and isn't related to your issue of Avahi services disappearing. I would still like to know if all your Avahi services disappear, or just the Homebridge-related one, because I still don't think your issue is related to Homebridge but I need your help proving (or disproving) that to go any further.

**Comment by adriancable** [comment]
> Interestingly, unlike Avahi, homebridge is not listening on IPv6 - maybe that is related to the issue I'm experiencing. It is also not clear to me why homebridge is listening to this port "twice".

In case you're interested, I have submitted a PR for @homebridge/ciao to enable IPv6 advertising: https://github.com/homebridge/ciao/pull/19

The PR also explains the rationale for this, mostly router compatibility.

Working on Starling Home Hub I have probably seen every imaginable failure mode for mDNS advertising! SHH has been using (a fork of) Avahi for a long time now for advertising HAP services and there are no known reliability issues with that.

**Comment by seidnerj** [comment]
I don't doubt anything you're saying, I am simply trying to understand why ciao does not exhibit the aforementioned behavior while avahi does, so am looking for clues in the differences I notice between the two. 

IPv6 is one such difference I noticed, though likely unrelated, I am checking it out as well. 

Something here is obviously not working as intended so I need to consider anything as a possible culprit. 

I will update the thread when I know more.

Thanks again.

**Comment by seidnerj** [comment]
Btw, if indeed I have ciao listening "twice" for two different addaptera then why would avahi not do the same? I only have eth0 (wifi is disabled) so it must be the loopback adapter or similar, I wonder if avahi simply excludes it.

**Comment by adriancable** [comment]
@seidnerj - Avahi and Ciao are not related and one should not expect there to be any similarities in behaviour, beyond what is required for RFC 6762 compliance. Things like what network interfaces to advertise on are down to the client. Ciao definitely advertises on the loopback as well, but from looking at lathiat/avahi on Github, it does appear that:

> Currently we disable the loopback interface unless no other interfaces are activated.

**Comment by seidnerj** [comment]
So far so good, more than 24 hours have passed and the .local addresses are still being advertised. Maybe the IPv6 setting did the trick? I'll keep tracking it and update in a few days.

**Comment by adriancable** [comment]
@seidnerj - what router are you using, and how is your Raspberry Pi connected to it, and how is the device you are using to browse mDNS services / HomeKit connected to it?

(Almost) all mDNS issues are due to router bugs, or incorrect router settings, or a network connection geometry issue.

**Comment by seidnerj** [comment]
I am using an Airport Extreme router, the RP is connected to a small 8-port
Netgear switch which in turn is connected directly to the Airport Extreme
so pretty simple network topology.

I terms browsing, I am using either my iPhone or Macbook via Wifi.

.local address is still currently accessible, if this stays the same in a
few days, I’m going to try and reenable IPv6 on Avahi and see if the
problem reappears.

**Comment by seidnerj** [comment]
Everything still works as expected. I've re-enabled IPv6 in Avahi and restarted the service. Will update the thread with my findings.

**Comment by seidnerj** [comment]
.local address is gone again!

This is Avahi's log:

```
pi@homebridge:~ $ sudo systemctl status avahi-daemon.service
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2022-02-19 12:31:53 IST; 1 day 23h ago
 Main PID: 23264 (avahi-daemon)
   Status: "avahi-daemon 0.7 starting up."
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/avahi-daemon.service
           ├─23264 avahi-daemon: running [homebridge-2.local]
           └─23265 avahi-daemon: chroot helper

Feb 21 11:42:28 homebridge avahi-daemon[23264]: Withdrawing address record for 2a0d:6fc2:4660:1300:f2c1:c707:3901:c619 on eth0.
Feb 21 11:42:28 homebridge avahi-daemon[23264]: Leaving mDNS multicast group on interface eth0.IPv6 with address 2a0d:6fc2:4660:1300:f2c1:c707:3901:c619.
Feb 21 11:42:28 homebridge avahi-daemon[23264]: Joining mDNS multicast group on interface eth0.IPv6 with address fe80::ef3c:e295:63c7:7b7d.
Feb 21 11:42:28 homebridge avahi-daemon[23264]: Registering new address record for fe80::ef3c:e295:63c7:7b7d on eth0.*.
Feb 21 11:42:28 homebridge avahi-daemon[23264]: Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::ef3c:e295:63c7:7b7d.
Feb 21 11:42:28 homebridge avahi-daemon[23264]: Joining mDNS multicast group on interface eth0.IPv6 with address 2a0d:6fc2:4660:1300:f2c1:c707:3901:c619.
Feb 21 11:42:28 homebridge avahi-daemon[23264]: Registering new address record for 2a0d:6fc2:4660:1300:f2c1:c707:3901:c619 on eth0.*.
Feb 21 11:42:28 homebridge avahi-daemon[23264]: Withdrawing address record for fe80::ef3c:e295:63c7:7b7d on eth0.
Feb 21 11:42:28 homebridge avahi-daemon[23264]: Registering new address record for fd3f:459a:1463:4da7:3e08:959d:6382:60cc on eth0.*.
Feb 21 11:47:20 homebridge avahi-daemon[23264]: Withdrawing address record for fd3f:459a:1463:4da7:3e08:959d:6382:60cc on eth0.
```

See attached screenshots.

![before](https://user-images.githubusercontent.com/4147381/154931660-04a68564-ca12-429d-87f8-e8aedb3e2405.jpg)

![after](https://user-images.githubusercontent.com/4147381/154931668-17a5edf2-3158-4c45-bf23-5bc3c0e9b364.jpg)

I'm going to disable IPv6 again and see if the address persists again.

**Comment by seidnerj** [comment]
Okay, this has happened again, even with IPv6 disabled. I'm giving up, going back to ciao. Don't understand why this is happening but don't have a good way forward. Thanks for everyone here who tried to help.

**Comment by Kentzo** [comment]
I also encountered this when migrated my installation from using vanilla homebridge to hb-service: I had `disallow-other-stacks=yes` in my avahi config file.

I wonder why is it necessary for hb-service to unconditionally have this listener as my previous installation worked find without it.

**Comment by admo** [comment]
hb-service listens on port 5353 because the [Accessory Control](https://github.com/homebridge/homebridge-config-ui-x/wiki/Enabling-Accessory-Control) feature is enabled.
This feature is managed through homebridge-config-ui-x, where there is an option to start Homebridge in insecure mode.
Enabling it triggers a chain of Node modules: [hap-client](https://www.npmjs.com/package/hap-client) → [bonjour-service](https://www.npmjs.com/package/bonjour-service) → [mdns](https://www.npmjs.com/package/mdns).
When hb-service starts its own browser on port 5353, after a few hours the local address of the host gets lost.
I'm not sure whether this is caused by the hb-service browser or the Homebridge advertiser running in insecure mode.
Nevertheless, disabling this feature resolves the issue.
