### ISSUE TITLE
Connecting to specific HomeKit hubs

### ISSUE THREAD

**Issue by andrewgould** [homebridge/homebridge#3088]
### Current Situation

I'm a UniFi Protect user who has gotten excited watching the progress around HKSV, and it's great to see that it's all finally singing in harmony.

In the lead up to today I spent some time playing with Scrypted, and although I wasn't able to get HKSV notifications working there, I did notice it had some really neat stuff going for it: specifically the ability to select HomeKit hubs to respond to.

In the HomeKit settings it has a section called Performance followed this little line:

> Optional: The addresses of your HomeKit Hubs. When HomeKit streams to outside of your local network, it is routed through a HomeKit hub. Scrypted can use a lower bitrate stream to keep your remote viewing session responsive.

The troubleshooting section had this:

> iPads and HomePods, which are wireless, are not reliable home hubs.

Although it doesn't say it outright, it's clear that specifying Ethernet-connected hubs is going to give a better result.

In testing my setup I put my phone onto 5G and connected to some of my cameras, and each time there was about a 5-10 second lag between me opening the video feed and the Homebridge logs actually acknowledging it. Video never appeared on the iPhone's screen until it was reflected in the logs. The logs mentioned a HomePod's IP address, which suggests that it's potentially got a bit of latency from basic hardware mixed with wifi latency.

If Homebridge were to have a way to select an Apple TV that's connected via Ethernet, I suspect this may alleviate some of the problems that I'm having here.

### Proposed Change

Scrypted has a configuration item that looks like this:
```
{
  "homekitHubs": ["192.168.1.220","192.168.1.148"]
}
```

My experience with Scrypted was it was lightning fast to connect me from the Home app to the video stream, regardless of if I was on my local network or not.

If we're able to specify IP addresses of Ethernet-connected HomeKit hubs it may be an opportunity to see faster Homebridge results, especially when it comes to video plugins.

**Comment by adriancable** [comment]
@andrewgould - I think you are misunderstanding Scrypted's feature. There is no way to select which HomeKit hub to use from the device side (= Homebridge or Scrypted). All of this happens behind the scenes, on the Apple side of fence, and is invisible/inaccessible to devices.

What Scrypted's setting does is changes the behaviour (like video bitrate) when it sees a connection request coming in from one of the IPs you specify. It doesn't have any influence over which device gets chosen to be your HomeKit hub.

If you are seeing (much) faster video stream starts with Scrypted it is probably because its HSV implementation uses a prebuffer, so it can start providing frames immediately as soon as the video request starts.

You will not find a meaningful difference in connection speed between a Wi-Fi HomeKit Hub and an Ethernet-connected one.
