### ISSUE TITLE
Grouped services don't show the name

### ISSUE THREAD

**Issue by JeroenVdb** [homebridge/homebridge#3197]
### Current Situation

I created the plugin https://github.com/JeroenVdb/homebridge-daikin-cloud which enables you to controle Daikin AC. I used the "Platform" type plugin approach.

The AC is controlled via a Heater Cooler service.
There are extra Switch services to enable certain features like "powerful mode" and "streamer mode".
All services are under the same accessory: "AC Kitchen" for example. Each service also has a name set like "powerful mode" or "streamer mode". See: https://github.com/JeroenVdb/homebridge-daikin-cloud/blob/master/src/accessory.ts#L6-L10 and https://github.com/JeroenVdb/homebridge-daikin-cloud/blob/master/src/accessory.ts#L76

Now the problem I'm facing is in the Home app interface. I don't see the names of the different services when I open the accessory en scroll past the switches. Is this maybe something missing in the Home app or am I doing something wrong? In multiple Youtube videos I've seen these names present.

My case (no name):
![180796757-03ed20a9-10b1-4b30-8a48-23e7915adf3e](https://user-images.githubusercontent.com/657797/180855204-b18c9a22-c722-46c5-b332-eacbe8d4ae1d.png)

How I would like it to be (names):
<img width="480" alt="Screenshot 2022-07-25 at 20 50 57" src="https://user-images.githubusercontent.com/657797/180855304-46de456e-c4f5-4f84-9779-eeffe5ee0034.png">

However when I go to accessories in the settings screen of the accessory, then I get a list of all services with their name. 

![180796737-65330caa-31a7-4373-946d-e05afdd069e4](https://user-images.githubusercontent.com/657797/180855610-7bc1d9b5-eb26-48f5-be13-ed3bd6052500.png)

So I guess I have set it up correctly but it does show it correctly somehow in the "overview" of the accessory. Is this fixable? Am I doing something wrong?

Full video (gif) of going through the accessory:
![179581436-b0827cef-875e-46bd-814e-be762393238b](https://user-images.githubusercontent.com/657797/180855662-932ec951-df2c-4024-b655-a39603fe6650.gif)

Related to a bug reported: https://github.com/JeroenVdb/homebridge-daikin-cloud/issues/15

### Logs

```markdown
Not applicable
```

### Configuration

```json
Not applicable
```

### Environment

- OS: Alpine Linux (3.15.4), raspberry pi
- Software: homebridge@1.4.1
- Node: v16.14.2
- npm: v8.5.0

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

Docker image used: https://github.com/oznu/docker-homebridge

**Comment by adriancable** [comment]
@JeroenVdb - iOS 14 and onwards don't show the names. There's nothing you can do about it, sorry.

When this behaviour change first appeared in an early iOS 14, I filed a ticket with Apple, which got ignored. So it is probably deliberate.

Apple is well known for using technical 'nudges' to force third party developers into particular patterns. In HomeKit a well known example is that there is (no longer) any way for a bridge to let HomeKit know that accessories are unavailable, the reasoning being that this 'legitimized' device downtime. By deliberately making the UX as terrible as possible when HomeKit devices have downtime, it forces device developers to focus more on reliability. Or so the argument goes.

I would guess that the iOS 14 change with device names is an Apple 'nudge' to reduce device UI clutter that can result when accessories publish multiple services of the same type, which is usually a result of exposing settings (instead of actions and sensors) as HomeKit devices, which Apple tells 'real' HomeKit device developers not to do (settings should be kept in the vendor apps), although you see it all the time in Homebridge devices where plug-in developers just do what they want. The rationale is that settings don't get changed often, but being there all the time add clutter / decrease usability for everyday device control.

I don't know what "powerful mode" and "streamer mode" mean for your device, but if these are just marketing terms for different fan speeds, then you can use a variable-speed fan control in HomeKit which indeed ends up as a much nicer UI than lots of switches.

**Comment by JeroenVdb** [comment]
Thanks @adriancable for the great explanation! It's good I now understand the "thinking" behind the Home app of Apple. I already advised my users to not enable the extra config switches and use the Daikin app itself for these settings. I now understand that also matches the philosophy of Apple.

I will keep those extra "fake" switches for settings behind a config flag. And a warning that enabling it will probably not improve the UX unless you know what you are doing.

Thanks again @adriancable!
