### ISSUE TITLE
Ubuntu/Debian repo has unexpected size

### ISSUE THREAD

**Issue by thatslolo** [homebridge/homebridge#3212]
### Current Situation

After adding repo to apt, apt can't get packages file. Since I added the repo two days ago this error persisted.
Had to install Homebridge via npm

### Logs

```markdown
sudo apt-get update

Get:9 https://repo.homebridge.io stable/main arm64 Packages [571 B]
Err:9 https://repo.homebridge.io stable/main arm64 Packages
  File has unexpected size (569 != 571). Mirror sync in progress? [IP: 2606:4700:3030::ac43:bd5d 443]
  Hashes of expected file:
   - Filesize:571 [weak]
   - SHA256:3f92f525556a7c36d9abec8949cddee3799c326f4d3b31e94b98cb0e561f6763
   - SHA1:8dee8ae430528e40047be91b284d01a36293c8ce [weak]
   - MD5Sum:be5730f61e7c09e153113b2fd116c2dd [weak]
  Release file created at: Sat, 16 Jul 2022 11:42:26 +0000
Get:10 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 Packages [1436 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 Packages [883 kB]
Fetched 2923 kB in 4s (701 kB/s)                           
Reading package lists... Done
E: Failed to fetch https://repo.homebridge.io/dists/stable/main/binary-arm64/Packages.gz  File has unexpected size (569 != 571). Mirror sync in progress? [IP: 2606:4700:3030::ac43:bd5d 443]
   Hashes of expected file:
    - Filesize:571 [weak]
    - SHA256:3f92f525556a7c36d9abec8949cddee3799c326f4d3b31e94b98cb0e561f6763
    - SHA1:8dee8ae430528e40047be91b284d01a36293c8ce [weak]
    - MD5Sum:be5730f61e7c09e153113b2fd116c2dd [weak]
   Release file created at: Sat, 16 Jul 2022 11:42:26 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Configuration

```json
curl -sSfL https://repo.homebridge.io/KEY.gpg | sudo gpg --dearmor | sudo tee /usr/share/keyrings/homebridge.gpg  > /dev/null

echo "deb [signed-by=/usr/share/keyrings/homebridge.gpg] https://repo.homebridge.io stable main" | sudo tee /etc/apt/sources.list.d/homebridge.list > /dev/null
```

### Environment

- OS: Ubuntu 20.04
- Software: 1.5.0
- Node: v18.7.0
- npm: 8.17.0

### Process Supervisor

other (Explain in `Additional Context`)

### Additional Context

Process supervisor not relevant in this context.

**Comment by oznu** [comment]
While I didn't try before refreshing the cache, I can't replicate this issue on arm64.

**Comment by thatslolo** [comment]
I just tried to reproduce it and it worked for me too.
The logs I provided were created while creating the issue. I don't know why it works now. ¯\_(ツ)_/¯ 

Nevertheless this issue seems obsolete

**Comment by oznu** [comment]
Maybe the Cloudflare cache purge didn't work properly after the last deploy? I'll keep an eye on things.

https://github.com/homebridge/homebridge-apt-pkg/actions/runs/2822793707

**Comment by alexandre-trottier** [comment]
I'm also getting this issue today.

**Comment by alexandre-trottier** [comment]
Getting this issue again today.

**Comment by Johnt5818** [comment]
Just got this today. 
```
root@homebridge:~# apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Get:3 https://repo.homebridge.io stable InRelease [3,242 B]
Hit:4 http://security.debian.org bookworm-security InRelease
Get:5 https://repo.homebridge.io stable/main amd64 Packages [2,614 B]
Err:5 https://repo.homebridge.io stable/main amd64 Packages
  File has unexpected size (2721 != 2614). Mirror sync in progress? [IP: 104.21.57.62 443]
  Hashes of expected file:
   - Filesize:2614 [weak]
   - SHA256:8c693726b69f2c6f3ce8e4dce188ba94091a496929e2598bc6534d91e0503842
   - SHA1:7dedfff80207f021d6fc3144919ae2167f6d881a [weak]
   - MD5Sum:218c0037baa88971d97a3dfbc6a91451 [weak]
  Release file created at: Mon, 30 Sep 2024 14:20:26 +0000
Reading package lists... Done
E: Failed to fetch https://repo.homebridge.io/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (2721 != 2614). Mirror sync in progress? [IP: 104.21.57.62 443]
   Hashes of expected file:
    - Filesize:2614 [weak]
    - SHA256:8c693726b69f2c6f3ce8e4dce188ba94091a496929e2598bc6534d91e0503842
    - SHA1:7dedfff80207f021d6fc3144919ae2167f6d881a [weak]
    - MD5Sum:218c0037baa88971d97a3dfbc6a91451 [weak]
   Release file created at: Mon, 30 Sep 2024 14:20:26 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Johnt5818** [comment]
Will do. Thanks.

**Comment by applefangirl** [comment]
I've been having the same problem since Monday (I'm trying to update the pihole, but so far no joy)

pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease                                 
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease                                           
Hit:4 http://archive.raspberrypi.com/debian bookworm InRelease                                          
Get:5 https://repo.homebridge.io stable InRelease [3,242 B]                                             
Get:6 https://repo.homebridge.io stable/main arm64 Packages [4,143 B]
Err:6 https://repo.homebridge.io stable/main arm64 Packages
  File has unexpected size (4031 != 4143). Mirror sync in progress? [IP: 2606:4700:3037::6815:393e 443]
  Hashes of expected file:
   - Filesize:4143 [weak]
   - SHA256:69f525f590cb57bbc810e3c53c410edf722fbf74d9addc8a26fe4d73d486743f
   - SHA1:01de28aab85634155f096b8b014304977d19326c [weak]
   - MD5Sum:a24b9d8d26b282d7bc6f311ef64ab2a6 [weak]
  Release file created at: Thu, 27 Mar 2025 14:48:36 +0000
Get:7 https://repo.homebridge.io stable/main armhf Packages [4,145 B]
Fetched 3,242 B in 2s (1,598 B/s)
Reading package lists... Done
E: Failed to fetch https://repo.homebridge.io/dists/stable/main/binary-arm64/Packages.gz  File has unexpected size (4031 != 4143). Mirror sync in progress? [IP: 2606:4700:3037::6815:393e 443]
   Hashes of expected file:
    - Filesize:4143 [weak]
    - SHA256:69f525f590cb57bbc810e3c53c410edf722fbf74d9addc8a26fe4d73d486743f
    - SHA1:01de28aab85634155f096b8b014304977d19326c [weak]
    - MD5Sum:a24b9d8d26b282d7bc6f311ef64ab2a6 [weak]
   Release file created at: Thu, 27 Mar 2025 14:48:36 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
