### ISSUE TITLE
Searching for a wifi outdoor humidity / temperature Sensor

### ISSUE THREAD

**Issue by Scoo27** [homebridge/homebridge#3284]
### Current Situation

Hi,
I am ne to homebridge / smarthome an searching for a sensor which I can easily integrate into HomeKit by using homebridge. 
a have a raspberry with homebridge and a few devices via DECT ULE (Switch and plug) via FRITZ!Box Plugin and a wifi WIZ plug successfully integrated. 

no I would like to integrate an outdoor sensor which is easy to setup an sends humidity and Temperature to the homebridge. 
has anyone an idea wich sensor I could buy?

i tried the eve Weather sensor,  but that connects only via Bluetooth or “thread” an needs a border Router like homepot or  tv (which I do not have) to get bridged into my wlan. 

Thanks 

### Logs

```markdown
—
```

### Configuration

```json
Raspberry Pi with homebridge installed
```

### Environment

- OS: homebridge
- Software: eve App and HomeKit on smartphone
- Node:
- npm:

### Process Supervisor

not applicable

### Additional Context

—

**Comment by mkormendy** [comment]
Interesting question, this isn't really the place for recommendations. This is for ISSUES (per the title) and bugs on the software.

Nonetheless, why don't you go for the native HomeKit sensor, here .. it's cheap and works amazingly well - batteries going on 6 months now.

https://www.amazon.com/gp/product/B08HCSB67Y/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by Scoo27** [comment]
thanks, @mkormendy 
didn't know that.

the linked sensor seems to be an indoor-sensor, as the article description says. i am searching for an outdoor one.
AND it works only via bluetooth, it seems (?)

**Comment by mkormendy** [comment]
Outdoor temperature/humidity sensor? Can't you use a weather plugin for homebridge for that?

**Comment by Scoo27** [comment]
no, i want to get the values right at my place (garden, carport etc.), not from a weather service (if i am getting you right?).

**Comment by mkormendy** [comment]
I am the developer of Homebridge Konnected .. it's a DIY alarm panel board that cuts the cord from your alarm provider and allows you to replace the traditional alarm panel in your house so you can monitor it yourself without paying for fees to an alarm service on HomeKit. (I mean how reliable are alarm service providers anyhow – police don't arrive for hours after anyhow in most places) on platforms like HomeKit).

You can set up one of the zone/ports on the board to a temperature and humidity sensor, but I don't know of a temperature and humidity sensor that works with it that is meant for outdoor (weatherproof).

But I'm sure there is .. because the konnected board can monitor the basic communication protocols for a DHT22 type sensor on one of its zones.

**Comment by Scoo27** [comment]
thank you
