### ISSUE TITLE
Homebridge is not responding in Homekit 

### ISSUE THREAD

**Issue by drhatemalfarra** [homebridge/homebridge#3304]
### Current Situation

Is there any problem with HB? Since last night all accessories are not responding om HK. PC, router, HomePod, switiches and everything restarted and work fine except the HB on HK. All accessories working on HB but not on HK

### Logs

```markdown
All accessories working on HB but not on HK
```

### Configuration

```json
those were working good, but since 12 hours ago the became not responding
```

### Environment

- OS: windows
- Software: HB
- Node: last version
- npm: last version

### Process Supervisor

hb-service

**Comment by kveton** [comment]
@drhatemalfarra Take a look at a few of the other issues threads. Looks like a common problem and one that is yet to be resolved unfortunately.

**Comment by donavanbecker** [comment]
Closing issue as we have no info on OS version, Homebridge Version, Node Version or NPM Version.

**Comment by kveton** [comment]
FYI - I did some more digging and it appears the issue was not Homebridge at all but my mDNS setup for local/internal devices. This causes the errors that people are seeing that make them think it is a homebridge issue. I suggest using a local network analysis tool to make sure your internal domains are resolving for the likes of *._tcp, etc.
