### ISSUE TITLE
IOS 16.5 -> Homebridge 1.6.1 -> device can not add to HomeKit , there is not compatible

### ISSUE THREAD

**Issue by Voisin030** [homebridge/homebridge#3373]
### Current Situation

I have a new installation of homebridge - with a Homebridge-image ,
homebridge work, but I can not connect to HomeKit. 
the issue is:
device can not add to HomeKit , there is not compatible.

thx2u

### Logs

```markdown
i have no error in the logs
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 1327",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51899,
        "pin": "xxx-xx-xxx",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "hosts": [
                "xx.xx.xx.40",
                "127.0.0.1:4530"
            ],
            "hueMotionTemperatureHistory": true,
            "lights": true,
            "linkButton": false,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "sensors": true,
            "users": {
                "user": "pass"
            },
            "wallSwitch": false,
            "platform": "Hue"
        },
        {
            "host": "xx.xx.xx.250",
            "port": 80,
            "username": "xxxx",
            "password": "xxxxxxx",
            "options": {
                "stairwellSwitch": "pulse",
                "moodSwitches": "none",
                "radioSwitches": 1,
                "alarmSystem": "delayedon",
                "alarmTrigerLevel": 5,
                "autoLock": 1,
                "autoLockDelay": 5
            },
            "platform": "LoxoneWs"
        },
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Home",
                    "videoConfig": {
                        "source": "-i rtsp://xx.xx.xx.xx:8554/mjpeg/1",
                        "stillImageSource": "none"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ],
    "disabledPlugins": [
        "homebridge-loxone-ws-adv-cstm"
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye
- Software: Homebridge
- Node: v18.16.0
- npm:

### Process Supervisor

hb-service

**Comment by JulyIghor** [comment]
The same for me, Homebridge stopped to work after iOS 16.5 update.
![IMG_8186BBB931B6-1](https://github.com/homebridge/homebridge/assets/3390357/7dff1204-d4f7-46fd-8700-ae425d0b5951)

**Comment by henry-bettany** [comment]
Same for me, ever since the iOS 16.5 update, Homebridge accessories have failed to respond. This is both before and after updating my HomePods to iOS 16.5 (from iOS 16.4.1). I've noticed that in the Home app, the Homebridge-attached accessories keep changing their names from the name I gave them to their internal device name.

**Comment by skr3328** [comment]
Same here. After updating to iOS 16.5b eta, all HomeKit accessories added via Homeassistant reported Not Responding. I then deleted the HomeKit Bridge entity in HA and tried to re-pair with Apple Home but got error messages. I also tried to pair with Homebridge and the bridge was successfully connected, however all accessories under the bridge were not responding. I updated my phone to iOS 16.6 beta today and the problem remains.

**Comment by JulyIghor** [comment]
> In my setup I'm running also running the iOS 16.6 beta, and am not having an issue.

I just wish to clarify this: when I updated phone to iOS 16.5 everything worked fine, but when I updated my hub (iPad) to iOS 16.5 it stopped to work, so the hub iOS version is only important.

**Comment by Voisin030** [comment]
Hello @NorthernMan54
yes it is the same message .

**Comment by NorthernMan54** [comment]
@Voisin030 I'm wondering if this setting in your hue plugin configuration could be causing the issue.

``` 
"127.0.0.1:4530"
```

As an approach to find the issue you could try `Child Bridges` and put each of your plugins into its own homebridge instance

https://github.com/homebridge/homebridge/wiki/Child-Bridges

**Comment by JulyIghor** [comment]
@NorthernMan54 I disabled all plugins except "Homebridge UI" and "Homebridge Dummy".
It is now possible to add homebridge to Apple Home, but once Home app restarted it disappear.

**Comment by JulyIghor** [comment]
I disabled this plugin and everything is working now
Homebridge Plex Webhooks (homebridge-plex-webhooks v2.2.0)

**Comment by JulyIghor** [comment]
> I disabled this plugin and everything is working now
> Homebridge Plex Webhooks (homebridge-plex-webhooks v2.2.0)

even that way, Bridge disappears from Apple Homekit some time later.

**Comment by NorthernMan54** [comment]
The bridge disappearing is very odd behavior, as you would normally get ‘Not Responding’ when the Home app is no longer able to connect to homebridge.

**Comment by JulyIghor** [comment]
> The bridge disappearing is very odd behavior, as you would normally get ‘Not Responding’ when the Home app is no longer able to connect to homebridge.

it disappears also if the only plugin enabled is "Homebridge UI".
Also after that, if I try to add the bridge again, it says it is already added, but in fact not visible.

**Comment by paulgab** [comment]
I too had a similar issue, since updating iOS, AppleTV and HomePod mini to latest OSs recently. Not sure when it started happening, maybe after a few days, all the hardware within Homebridge when into not responding error.

Removing the Homebridge bridge in Home and re-adding is working for now.

**Comment by benoitma** [comment]
Same here after upgrading to 16.5. Removed bridge from Home app but re-adding does not add accessories anymore

**Comment by tennr** [comment]
Same here... Homebridge devices are "No Response" since updating to 16.5

**Comment by Voisin030** [comment]
Hello,
I have deactivated all plugins, the reconnect this Bridge to HomeKit. The connection is working. But after activating the plugins, HomeKit has no devices from homebridge.

**Comment by RawShore** [comment]
Same here, updated yesterday everything is dead. Recognized that configuration key number and syntax changed.

![image](https://github.com/homebridge/homebridge/assets/104089235/baea0c49-e1ae-482e-99ec-b62577d19c66)

**Comment by lily148** [comment]
FYI, I am using Homebridge 1.4. Updated iOS 16.5 and HomePod to version 16.5 as well. No problem so far.

**Comment by RawShore** [comment]
> FYI, I am using Homebridge 1.4. Updated iOS 16.5 and HomePod to version 16.5 as well. No problem so far. 
> 
> 

Try to add an new bridge.

**Comment by cheme75** [comment]
I recently upgraded to iOS 16.5, added a new device as child bridge and so far all is good. I’m on 1.5.1 since I don’t want to take the time to update lubuntu from 18.04. As long as all is working ok, I’m holding off on updating.

**Comment by ody** [comment]
I noticed that my Levoit Air Purifiers were not longer responding in the Home app after the upgrade to 16.5 and decided to remove the the child bridge that the plugin was running within, upon trying to re-add the bridge I got the "not compatible" message described in this ticket. As a last ditch effort I removed the plugin entirely and let it also delete the plugin's `config.json`. After re-installing the plugin and assigning it a new child bridge, the bridge added cleanly and air purifiers once again respond in the Home app.

**Comment by JulyIghor** [comment]
Exactly the same issue is reproduced on HomeAssistant also, so most likely it isn't related to Homebridge, but any fix would be good to find.

**Comment by homeautomationch** [comment]
Brand new New homebridge setup today ios 16.5.1, Synology running homebridge 1.6.1 off docker… Apple home does not allow add accessory manually or via QR code same error message as https://github.com/homebridge/homebridge/issues/3373#issuecomment-1558438317
I think we urgently need a fix for this new ios / Home version we know Apple somewhat mandates updates > any chance an someone could please prioritise… i see several forums talking of this issue and not yet realising it is cuteness incompatible. 😢

**Comment by NorthernMan54** [comment]
@JulyIghor I spent some time today with a new install of the RPI Homebridge Image in an attempt to recreate your issue without any success.

Is it possible to share a Homebridge UI backup of your setup via a Homebridge Discord DM ?  Am thinking that an accessory or plugin within your config is causing this.

**Comment by JulyIghor** [comment]
> Is it possible to share a Homebridge UI backup of your setup via a Homebridge Discord DM ? Am thinking that an accessory or plugin within your config is causing this.

Hi. I deleted config folder, and added HomeBridge to HomeKit with no settings changed. I always get it reproduced.
I can share access to everything needed if it helps to reproduce it.

**Comment by NorthernMan54** [comment]
Is the message you are getting still this - https://github.com/homebridge/homebridge/issues/3373#issuecomment-1558438317

**Comment by JulyIghor** [comment]
> Is the message you are getting still this - https://github.com/homebridge/homebridge/issues/3373#issuecomment-1558438317

I seen it once. But now this is happening:
1) I add freshly installed HomeBridge to HomeKit
2) Works fine for 2 minutes
3) Bridge and all accessories disappear from HomeKit

**Comment by NorthernMan54** [comment]
When you say freshly installed Homebridge, what plugins etc do you have.   Can you share a UI Backup via the homebridge discord and a direct message ? I would hope that installing your backup will allow me to recreate the issue.  ( Am thinking something in your config is causing HomeKit to reject your setup )

**Comment by homeautomationch** [comment]
Brand new New homebridge setup today ios 16.5.1, Synology running homebridge 1.6.1 off docker… I cant add to Apple homekit manually or via QR code... each time after a long wait I get "Accessory not Found".
FYI.. Interestingly also tried HomeAssistant and same experience.

**Comment by GithubUser-XX1** [comment]
HomePod 16.5 is a mess. It bricked by HomePod OG, and Apple will do nothing to fix it except sell me the newest one for ~$220. I'm not rewarding them with any more money for their buggy code.

I'm setting up HomeBridge for the first time in the Apple Home app. It goes through the motions when I try to add an accessory, but HomeBridge never shows in the list of bridges under Home.

**Comment by adriancable** [comment]
There are so many completely different issues here. Please help us to help you by not posting new issues in a GitHub thread that's about a different issue. If you have a different issue, create a new GitHub issue. Otherwise it's impossible to follow.

@JulyIghor - devices adding successfully then disappearing a couple of minutes later (when the phone does an iCloud sync) is an endpoint/iCloud cache coherency issue. If you are using iOS 16.5, there is a known bug whereby adding new devices if you are not the home 'owner' causes this. My 95% guess is this is your issue. Other 5%: sign out of iCloud on your iPhone and HomeKit hubs, then back in. This will rebuild the internal HomeKit state.

@homeautomationch - this is not a Homebridge (or Home Assistant) issue. If you can access the Homebridge machine (e.g. the UI) by IP but not add to HomeKit, 100% of the time it means you have a multicast routing issue on your network. First step is to run Homebridge natively on your machine - not in Docker or a VM. If that doesn't fix things (and 80% of the time it will not), it means your network isn't set up to route multicast traffic properly. Home routers purchased in the last 5 years will do this automatically, and not require any setup. If you are using an enterprise router setup/VLANs/discrete APs/etc. you will need to set up multicast forwarding between the network segments. Look for settings called 'multicast DNS', 'IGMP proxy', 'IGMP enhancement' etc. and set those correctly. If this is beyond your ability, just get a good mesh network e.g. Eero or Google Wi-Fi and everything will 'just work' out of the box.

@badriram - you also have a multicast routing issue. After adding devices to HomeKit on your iPhone, if you are using the 'new architecture', as soon as an iCloud sync occurs (usually 1-2 minutes after adding), control will transfer from iPhone->device to active HomeKit hub->device. If your iPhone can reach your Homebridge machine via mDNS but your active HomeKit hub cannot reach your Homebridge machine via mDNS, then devices will add OK but after a minute or two, go to 'No Response'. See my comment to @homeautomationch.

Finally, 'out of compliance' means that the device is initially setting characteristics outside the allowed range. For example a thermostat reporting a temperature of -9999 will produce this message. It is a plug-in issue. Find the responsible plug-in using any method of your choice (bisect, remove one by one, etc.) and reach out to the plug-in author. iOS releases tend to be more strict enforcing this as time goes on, and iOS 16.5 validates more comprehensively than iOS 16.4. It is not a Homebridge issue.

**Comment by JulyIghor** [comment]
> @JulyIghor - devices adding successfully then disappearing a couple of minutes later (when the phone does an iCloud sync) is an endpoint/iCloud cache coherency issue. If you are using iOS 16.5, there is a known bug whereby adding new devices if you are not the home 'owner' causes this. My 95% guess is this is your issue. Other 5%: sign out of iCloud on your iPhone and HomeKit hubs, then back in. This will rebuild the internal HomeKit state.

Thanks, I'm not sure was it the reason or no, but i added new home, tried to add it there, removed the new home and everything started to work with my current home.

**Comment by henry-bettany** [comment]
Bump to keep the issue going stale as lots of people are having the problem.

**Comment by Xenovalis** [comment]
Still having the issue in 16.6 Release (20G75)
