### ISSUE TITLE
Feature to switching off a child bridge 

### ISSUE THREAD

**Issue by vivekanandbv** [homebridge/homebridge#3416]
### Current Situation

Some plugins continuously send requests to IoT devices to update status of the device in home app, even though the device is switched off. One such plugin is homebridge-http-webhooks which sends http requests (status url) regularly to update the status of a switch/sensor. If the sensor is switched off, the http request returns an error to the log repeatedly, which overloads home bridge, slowing it down, despite making a child bridge for the switch/sensor.

### Proposed Change

A feature to switch off a child bridge temporarily and switch it on whenever required will solve the problem. The child bridge may be switched off/on using http web hooks, which can be exposed as a stateless switch in home app. this not only is a solution, but also provides opportunity to create automations to switch off/ on the child bridges.

**Comment by NorthernMan54** [comment]
Switching off or disabling a child bridge is available via the UI, on the plugin page under the each plugins wrench icon.

If a plugin is causing issues, it is an issue that the plugin developer needs to investigate.

**Comment by SawkeeReemo** [comment]
Let’s re-open this. The entire point of using tools like Homebridge is to help us with automation. And I have an issue at home with a device that I use a HB plugin to control. The device needs to be turned off every night due to some weird firmware issue that who knows when they will fix it. 

But because I can’t automate shutting off the child bridge when my device cannot be pinged, I have to now remember to manually shut down and restart the child bridge every day or my HB logs are spammed into oblivion with errors about a connection being lost. 

That’s the opposite of automation. We should have the ability to either by automation or script shut down a child bridge based on whatever rules we want to set. This should not just be dismissed with a completely inaccurate and short-sighted response with no further consideration.

**Comment by NorthernMan54** [comment]
@SawkeeReemo my comment from a few years ago should still apply - If a plugin is causing issues, it is an issue that the plugin developer needs to investigate.

**Comment by SawkeeReemo** [comment]
> [@SawkeeReemo](https://github.com/SawkeeReemo) my comment from a few years ago should still apply - If a plugin is causing issues, it is an issue that the plugin developer needs to investigate.

I agree. But in this case it’s not the plugin that’s causing the issue. It’s a device that Homebridge is controlling that needs a firmware update which as you know could take months. 

To mitigate the issue, I have to power off (like pull the plug out of the wall; use a smart switch) the device every night. Then the plugin is trying to connect to it and spamming the logs, which is not a bug. We want to know in the logs when a device cannot be reached, right?

But since I know what the issue is, and there’s nothing a plugin can do to correct this, I could write a simple script to run that triggers the child bridge to turn off/on along with my device so that I don’t have to do it manually.

It’s a simple fix to a problem that cannot be solved by us, and allows for a power user to be able to have better automation when needed. 

Does that make sense?
