### ISSUE TITLE
Best way to move plugin to a child bridge

### ISSUE THREAD

**Issue by MirkoKas** [homebridge/homebridge#3430]
### Current Situation

I'm running homebridge for a long time and therefore have some plugins that I installed before child bridge support was added.
I'm wondering what's the preferred way to move an established plugin (and it's devices) to a child bridge with the least trouble concerning changing automations and so on.

### Process Supervisor

hb-service

**Comment by bwp91** [comment]
Hi @MirkoKas 

There is no way of _migrating_ a plugin from the main bridge to a child bridge.

Unfortunately this will mean that all the related accessories will be removed and re-added to homebridge (and homekit - thus the _reset_ of all devices).

The homekit reset of devices will mean yes you will need to reconfigure all the device scenes/automations again.

So to answer your question, there is no 'approved way' of moving devices since there isn't even a 'way'.

My recommendation would be to just bite the bullet, take each of your plugins in turn and re-configure to use a child bridge, re-set up the automations in the home app.

**Comment by MirkoKas** [comment]
Thx. that was the answer I was expecting and how I handled it in the past, but I hoped I was just missing something.
