### ISSUE TITLE
Modify config.json from a plugin itself

### ISSUE THREAD

**Issue by maxileith** [homebridge/homebridge#3486]
### Current Situation

Is it possible to modify the config.json from within the plugin?

I am a developer and want to trigger an operation at startup when there is a certain attribute in the config.json set to true. After booting up and doing the operation, I want to set the value to false in the config.json programmatically. Is there a way to accomplish that or is that considered bad practice for a Homebridge Plugin?

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by maxileith** [comment]
Not stale

**Comment by bwp91** [comment]
Hi @maxileith first of all I would say that I _personally_ would try to avoid doing this, and is something that I never do in my plugins (firstly because I don't have the need, but secondly I would try to find workarounds).

However, yes, technically it is possible. I know that the ring plugin does this (i can't remember why) but I scouted out the function which does this there:

https://github.com/dgreif/ring/blob/4b4e5611bafddc8ca4ad5baba35335c05879b5cc/packages/homebridge-ring/config.ts#L29

The reason I (personally) don't like this is for the obvious reasons

- what if the write to the config file fails somehow? is there some fallback? and if the fallback fails?
- what if the function is not tested properly and writes something incorrectly?

What is it that you are trying to accomplish and is there any way of avoiding the change to a user config file?

**Comment by maxileith** [comment]
Hi @bwp91,

the main reason why I am asking this is a function of [homebridge-appletv-enhanced](https://github.com/maxileith/homebridge-appletv-enhanced), where the user can check a box in the settings UI to force the recreation of the python venv on startup in case something is wrong with that.

It would be ideal if the plugin would uncheck that box after the first restart of the plugin so the python venv is not created on every startup. In order to do that, it would be required to set the regarding config attribute programatically. The solution of the Ring plugin already come to my mind and is fairly straight forward. However, as you already said ... this is not a clean solution at all. I was hoping for a more elegant way.

However, after https://github.com/homebridge/homebridge-config-ui-x/issues/1955 has been solved, I cannot really think of any situation where a recreation of the python venv is required, besides faulty installations. I have already thaught about removing this option entirely. Nevertheless, if you got a nice solution to that problem, I am open to that.
