### ISSUE TITLE
Constant updating of accessories

### ISSUE THREAD

**Issue by whitevast** [homebridge/homebridge#3492]
### Current Situation

Homebridge constantly requests the update of the accessaries without using the cache. Since I use the MQTT plugin for communication, I can observe more than 1000 requests through MQTTExplorer every time I open a page with accessories. The same behavior when HomeKit on iPhone executes Smart Home requests. Is it possible to disable persistent requests using the Homebridge cache? All changes in the states of accessories are sent to Homebridge anyway, so why constantly poll all accessories, loading MQTT and the smart home system?

### Proposed Change

Updating the states of accessories from the Homebridge cache.

**Comment by NorthernMan54** [comment]
This is a question for the plugin developer, as homebridge plugin api has the ability to accept push updates from the plugin/device or pull current status from the device.  Looks like the plugin you are using is using the get interface ( pull ) rather than the updateStatus ( push ) interface.

The usage of the push interface requires that the device has the ability to push status updates rather than pull them.  Not all devices / interfaces support this.

**Comment by whitevast** [comment]
The plugin is used by homebridge-mqtt v1.0.1, but it seems to me that it's not about the plugin. How I see the process: The accessories page opens (or HomeKit on iPhone requests an update). Next, Homebridge requests an update via the MQTT plugin. And it receives states through it (As I said, all this takes more than 1000 MQTT messages).
The latter actions can be excluded by taking states from the Homebridge cache. Why pull the plug-in every time to poll the states of all accessories? In any case, the cache of states is kept up-to-date, since when the statuses of the accessories change, this is immediately transmitted to Homebridge.
