### ISSUE TITLE
Set static IP address in HomeBridge GUI

### ISSUE THREAD

**Issue by FrankCellini** [homebridge/homebridge#3512]
### Current Situation

Seems difficult to change to Static IP address

### Proposed Change

Create ability to set static IP address in HomeBridge GUI

**Comment by bwp91** [comment]
Hi @FrankCellini 

It would always be recommended to use your router settings to provide a dedicated/static IP address to (for example) a raspberry pi that is running homebridge.

Since there is _recommended_ approach to what you have suggested, I am going to close this issue.

Of course, please feel free to object to what I have said and re-open!!

Cheers

**Comment by a-rock-lobster** [comment]
Hi @bwp91 
My ISPs router doesn't allow for setting static IP addresses. One can set an IP address range, though. So I'm currently trying to figure out how to set a static IP address on my homebridge pi. 
It is a rare, but not nonexistent use case for setting the static IP on the pi rather than the router. 
Best,

**Comment by cheme75** [comment]
> Hi @bwp91 
> My ISPs router doesn't allow for setting static IP addresses. One can set an IP address range, though. So I'm currently trying to figure out how to set a static IP address on my homebridge pi. 
> It is a rare, but not nonexistent use case for setting the static IP on the pi rather than the router. 
> Best, 

I set "static" ip on my isp router and this new centurylink fiber modem/router is a royal pain. I've had it crash trying to port fwd. Anyway, I think they call it reserving an address. I set my NAS to a certain ip then in the router I reserve it for that device. I only got a few since most things retain the dhcp assigned address.

**Comment by a-rock-lobster** [comment]
On the router supplied by my ISP you cannot reserve IP addresses for devices. There are very few settings. Very frustrating. I don't like just throwing money at a problem but buying my own router seems the only way.

**Comment by cheme75** [comment]
> On the router supplied by my ISP you cannot reserve IP addresses for devices. There are very few settings. Very frustrating. I don't like just throwing money at a problem but buying my own router seems the only way. 

At previous house I bridged a router as an access point via ethernet to use on same subnet along with the isp router so I could manage my wifi devices easier. It actually worked well. It was a bit older A-C router, but none of the devices needed A-C or A-X. Not sure what might be using A-X now besides my phone.
