### ISSUE TITLE
PETLIBRO Support

### ISSUE THREAD

**Issue by gabber366** [homebridge/homebridge#3597]
### Current Situation

I am unable to find any Plugins that support Petlibro devices. Suggesting this for anyone who is interested.

### Proposed Change

Creation of a Plugin that supports Petlibro Devices:

- HomeKit Camera support for Feeders with two way Cameras.
- Switch to activate a manual feeding.

### Additional Context

More info on Petlibro here: https://petlibro.com

**Comment by bwp91** [comment]
Hey @gabber366 

Thanks for sharing your suggestion!

Just to clarify, the 'issues' section here on GitHub is mainly for reporting problems or suggesting features directly related to the Homebridge application itself, rather than for plugins.

Since all Homebridge plugins are developed by the community, you might find it more effective to reach out on our Reddit or Discord servers for plugin-related requests.

I'll go ahead and close this issue for now. But feel free to get in touch if you have any other questions or ideas!

Cheers
