### ISSUE TITLE
Upgrade to 1.8.0 fails

### ISSUE THREAD

**Issue by gorbi2001** [homebridge/homebridge#3602]
### Current Situation

I'm not able to upgrade to 1.8.0 from the gui.
Plugin installs and upgrades work as expected.

Can not determine where the "nonexistant" directory is referenced

### Logs

```markdown
USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge@1.8.0

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /nonexistent
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/nonexistent'
npm ERR!  [Error: EACCES: permission denied, mkdir '/nonexistent'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/nonexistent'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! Log files were not written due to an error writing to the directory: /nonexistent/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

### Configuration

```json
-
```

### Environment

- OS	Debian GNU/Linux Bookworm (12)
- Node.js Version	v20.12.2
- Node.js Pfad	/opt/homebridge/bin
- Speicherpfad	/var/lib/homebridge
- Konfigurationspfad	/var/lib/homebridge/config.json
- Pluginpfad	/var/lib/homebridge/node_modules

### Process Supervisor

hb-service

**Comment by bwp91** [comment]
Hi @gorbi2001 

Looks like the same error as here:
 - https://github.com/homebridge/homebridge/issues/3480

Can you try the steps in that issue to see if this resolves?

**Comment by gorbi2001** [comment]
Thx @bwp91 

purge , reinstall & restore backup
did the trick.

**Comment by 4rianton** [comment]
didn't work for me.. 

> Thx @bwp91
> 
> purge , reinstall & restore backup did the trick.

**Comment by dennisdoose** [comment]
I get the following error message and can't get out where I make a mistake when I can update. I do the commands with Sudo in the terminal there are no problems.

USER: dennisdoose
DIR: /usr/local
CMD: npm install -g homebridge-meross@10.8.0
[?25l
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps

[?25h
npm
ERR! code EACCES
npm ERR!
 syscall open
npm
 ERR! path /Users/dennisdoose/.npm/_cacache/tmp/fef48037
npm ERR!
 errno -13
npm ERR!
 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm
ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm
 ERR! To permanently fix this problem, please run:
npm
ERR!   sudo chown -R 501:20 "/Users/dennisdoose/.npm"
npm
 ERR! A complete log of this run can be found in: /Users/dennisdoose/.npm/_logs/2024-11-27T17_57_49_815Z-debug-0.log


Error: Operation failed with code 243.

You can download this log file for future reference.

See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

**Comment by NorthernMan54** [comment]
Did you try the recommended fix from the error message `sudo chown -R 501:20 "/Users/dennisdoose/.npm"`
