### ISSUE TITLE
Error: send EAFNOSUPPORT 224.0.0.251:5353

### ISSUE THREAD

**Issue by NorthernMan54** [homebridge/homebridge#3621]
### Analysis

Seen this come up a couple of times recently from Reddit

I'm running homebridge on my Mac. This is what I see in the logs:

Error: send EAFNOSUPPORT 224.0.0.251:5353
    at doSend (node:dgram:719:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
    at afterDns (node:dgram:665:5)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Got SIGTERM, shutting down Homebridge...
Now, I'm generally pretty savvy, but this error doesn't turn up anything useful in google. I've tried reinstalling homebridge (after uninstall), tried deleting all homebridge files to start from scratch with configuration. I even tried deleting and reinstalling node. None of this has made a difference, homebridge, even on a clean install with no packages other than the UI will error out repeatedly.

### Expected Behavior

Homebridge should work

### Steps To Reproduce

Personally can't reproduce

### Logs

```markdown
Error: send EAFNOSUPPORT 224.0.0.251:5353
    at doSend (node:dgram:719:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
    at afterDns (node:dgram:665:5)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Got SIGTERM, shutting down Homebridge...
```

### Configuration

```json
Tbd
```

### Environment

- OS:  MacOS
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

### Additional Context

https://www.reddit.com/r/homebridge/comments/1d01w5e/homebridge_crashes_on_startup/

https://www.reddit.com/r/homebridge/comments/1bwy9ik/my_homebridge_has_suddenly_stopped_working/

**Comment by ebaauw** [comment]
Haven’t seen this myself.  Still developing plugins and running Homebridge on latest macOS on M2 Mac mini.

The error means: address family not supported, suggesting the issue is that the host on which this error appears doesn’t support IPv4.  This seems unlikely.  I tried disabling IPv4 on both my Ethernet and WiFi interfaces, to reproduce this issue, but got many host not found / cannot resolve errors instead.

Note that the (multicast) address and port are used for mDNS.  My guess: this has nothing to do with Homebridge (or rather: the mDNS advertiser), but with some (firewall or sandbox?) settings, disallowing the use of multicast.  It would be helpful to know what happened just before “suddenly”: like a macOS update or configuration change?  Maybe it’s related to certain network interfaces?

**Comment by Th3Crow** [comment]
Thanks so much ebaauw for your expertise and insights - they are greatly appreciated.
I'm "yet another" guy with the issue, but I thought I'd give you a bit more info. I got this same error right from the beginning; Homebridge just kept restarting, logging that EAFNOSUPPORT error, repeat.  I opened the settings and thought I'd change the network interface from "automatically detect" explicitly to en0, my ethernet connection (I have a second IP with WiFi). This seemed to calm things down considerably, and Homebridge stopped its reboot loop. I restarted and everything seemed okay for awhile.

The error happened just now. Eight minutes ago Homebridge reported:
"Running job to cleanup config.json backup files older than 60 days..."

After the eight minutes, I got the dreaded error:
Error: send EAFNOSUPPORT 224.0.0.251:5353 at doSend (node:dgram:719:16) at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18) at afterDns (node:dgram:665:5) at processTicksAndRejections (node:internal/process/task_queues:83:21)

While writing this, it happened again...and it was not running the cleanup job. It was 2 minutes after the restart and didn't seem to be doing anything obvious. I have now reset everything, and restarted again; after 5 minutes it's still solid. Oops - there it goes at the 6 min mark. And again after 15 seconds. Crap - again after another 30 seconds.

I can't understand what's triggering it - does it have anything to do with pairing to HomeKit?  Before I started writing this message, I thought perhaps it was happening each time I scanned the QR code to add Homebridge to my home app via my iPad. I hadn't tried that again for the duration of this text, but could it be trying without me manually attempting to pair it? The first time I DID try to pair it, the Home App told me it was already paired - but I hadn't done anything, and I couldn't see it anywhere. I removed it, but haven't been successful trying to pair it again.
If you have any suggestions or would like me to try something, I'd love to hear from you. I'm pretty frustrated and stuck - ready to give up on Homebridge - so any ideas are welcome. lol!

(I'm using a 2023 Mac Studio M2 Max on Sonoma 14.5)
Cheers,
Crow

**Comment by ebaauw** [comment]
HomeKit accessories, including Homebridge, advertise themselves over mDNS (previously known as Bonjour).  This protocol uses the 244.0.0.251 multicast IPv4 address and port 5353.  It’s not routable, i.e. it only works on the local subnet (that’s why Homebridge, your Home hub, and iDevices need to be on the same network).  To control accessories, HomeKit just uses HTTP (with some Apple-specific encryption); each accessory, including Homebridge, contains a web server.  This protocol is perfectly routable, but HomeKit will only connect to the web server after it’s seen the mDNS advertisement.

Each accessory keeps track weather it’s already paired.  If HomeKit has lost the accessory, but the accessory still thinks it’s paired, you need to factory-reset the accessory.  For Homebridge, this means deleting the `persist` directory.  The mDNS advertisement should include whether the accessory has already been paired (so HomeKit only lists unpaired accessories when searching for a new one), but sometimes this seems to go wrong.

The mDNS advertisements are handles by a separate component in Homebridge (or rather in HAP-NodeJS): the advertiser.  In the old days, this used to be a C++ extension, causing all sorts of installation problems (since the extension needed to be compiled on each installation).  Nowadays, there are a number of alternative advertisers, like Bonjour-HAP, ciao, and an integration with the Linux Avahi daemon.

I suspect the error originates from the mDNS advertiser, not from Homebridge itself (nor from any plugin).  Your remark on limiting to `en0` makes me think that maybe the advertiser tries to advertise on another network interface, without support for IPv4, or maybe for multicast.  Could be the loopback interface (`lo0`), a Thunderbolt connection between two Macs, or maybe some virtual interface for a VPN or for virtual machine or container software.

As per the documentation, the network setting in config.json should apply to both the HTTP server as well as to advertisements, but maybe something goes wrong here.  Possibly when new network interfaces appear after Homebridge was started.

**Comment by jeffhatz** [comment]
I've been having a similar issue where anytime I restart Homebridge, my log is constant errors that contain "EAFNOSUPPORT" for hours before eventually settling down. HB devices are unresponsive for ~30-60 minutes after a restart. Logs attached: one is normal with 4 plugins enabled, another is all plugins disabled where the issue persists but not as spammy.

This is relatively recent, I think it started in the last few months.

[Log Full.txt](https://github.com/user-attachments/files/15538179/Log.Full.txt)
[Log No Plugins.txt](https://github.com/user-attachments/files/15538181/Log.No.Plugins.txt)

**Comment by NorthernMan54** [comment]
@jeffhatz Can you share the network config of en0 and en1 ?

Mine

![image](https://github.com/homebridge/homebridge/assets/19808920/312fed1c-3514-4fe2-bd20-94c8a284531b)


en0: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=50b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV,CHANNEL_IO>
	ether f0:18:98:e9:5e:c7 
	inet6 fe80::1482:1181:7225:1e65%en0 prefixlen 64 secured scopeid 0x4 
	inet 192.168.1.122 netmask 0xffffff00 broadcast 192.168.1.255
	inet6 fd5c:cf30:2a11:c1dc:45d:295b:c730:69c6 prefixlen 64 autoconf secured 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex,flow-control,energy-efficient-ethernet>)
	status: active

en6: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether ac:de:48:00:11:22 
	inet6 fe80::aede:48ff:fe00:1122%en6 prefixlen 64 scopeid 0x5 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
en7: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether e0:4f:43:8a:61:19 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (none)
	status: inactive
ap1: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 3a:f9:d3:1a:17:b4 
	media: autoselect
	status: inactive

en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6463<RXCSUM,TXCSUM,TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 38:f9:d3:1a:17:b4 
	inet6 fe80::1cf8:d3ae:791d:a83b%en1 prefixlen 64 secured scopeid 0x8 
	inet 192.168.1.138 netmask 0xffffff00 broadcast 192.168.1.255
	inet6 fd5c:cf30:2a11:c1dc:1093:e3f8:db81:265d prefixlen 64 autoconf secured 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active

**Comment by jeffhatz** [comment]
@NorthernMan54 

![Screenshot 2024-06-05 at 2 55 33 PM](https://github.com/homebridge/homebridge/assets/1778967/6e800a62-11fb-4451-83ce-278bed24a059)

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128 
	inet6 XXXX::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>

gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280

stf0: flags=0<> mtu 1280

EHC253: flags=0<> mtu 0

EHC250: flags=0<> mtu 0

en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=50b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV,CHANNEL_IO>
	ether XX:XX:XX:XX:XX:XX
	inet6 XXXX::XXXX:XXXX:XXXX:41fc%en0 prefixlen 64 secured scopeid 0x6 
	inet 10.31.1.11 netmask 0xffffff00 broadcast 10.31.1.255
	inet6 XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX prefixlen 64 autoconf secured 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex,flow-control,energy-efficient-ethernet>)
	status: active

en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether XX:XX:XX:XX:XX:XX
	inet6 XXXX::XXXX:XXXX:XXXX:XXXX%en1 prefixlen 64 secured scopeid 0x7 
	inet 10.31.1.195 netmask 0xffffff00 broadcast 10.31.1.255
	inet6 XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX prefixlen 64 autoconf secured 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active

awdl0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether XX:XX:XX:XX:XX:XX
	inet6 XXXX::XXXX:XXXX:XXXX:XXXX%awdl0 prefixlen 64 scopeid 0x8 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active

llw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether XX:XX:XX:XX:XX:XX
	inet6 XXXX::XXXX:XXXX:XXXX:XXXX%llw0 prefixlen 64 scopeid 0x9 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active

en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether XX:XX:XX:XX:XX:XX
	media: autoselect <full-duplex>
	status: inactive

bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether XX:XX:XX:XX:XX:XX
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 10 priority 0 path cost 0
	media: <unknown type>
	status: inactive

utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet6 XXXX::XXXX:XXXX:XXXX:XXXX%utun0 prefixlen 64 scopeid 0xc 
	nd6 options=201<PERFORMNUD,DAD>

utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 XXXX::XXXX:XXXX:XXXX:XXXX%utun1 prefixlen 64 scopeid 0xd 
	nd6 options=201<PERFORMNUD,DAD>

utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 XXXX::XXXX:XXXX:XXXX:XXXX%utun2 prefixlen 64 scopeid 0xe 
	nd6 options=201<PERFORMNUD,DAD>

utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1000
	inet6 XXXX::XXXX:XXXX:XXXX:XXX%utun3 prefixlen 64 scopeid 0xf 
	nd6 options=201<PERFORMNUD,DAD>

vmenet0: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 16:e0:89:8e:7e:57
	media: autoselect
	status: active

bridge100: flags=8a63<UP,BROADCAST,SMART,RUNNING,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether XX:XX:XX:XX:XX:XX
	inet 192.168.64.1 netmask 0xffffff00 broadcast 192.168.64.255
	inet6 XXXX::XXXX:XXXX:XXXX:XXXX%bridge100 prefixlen 64 scopeid 0x13 
	inet6 XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX prefixlen 64 autoconf secured 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: vmenet0 flags=10803<LEARNING,DISCOVER,PRIVATE,CSUM>
	        ifmaxaddr 0 port 18 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active

utun4: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1200
	inet 10.21.11.252 --> 10.21.11.252 netmask 0xffffff00
	nd6 options=201<PERFORMNUD,DAD>

**Comment by NorthernMan54** [comment]
Are you running a VPN or something like that ?

**Comment by jeffhatz** [comment]
@NorthernMan54 Normally yes, including when that was taken. Prior to that for testing, I completely uninstalled the VPN and disabled iCloud private relay, and still had the issues.

The normal VPN configuration only sends limited traffic through the VPN, and everything else over the network as normal. Homebridge should be unaffected, and not going through the VPN. I’ve had that setup for much longer than this issue has existed.

**Comment by NorthernMan54** [comment]
I presume you have tried the other mDNS advertisers?

Am thinking we need to add more logging around this, so we can determine which network interface on your Mac is being used, and potentially why it is being triggered.

**Comment by NorthernMan54** [comment]
Am thinking the VPN may be triggering this, can you share what VPN you are using ? Want to install it within my test environment, to see if I can recreate it.

**Comment by Th3Crow** [comment]
I'm tearing my hair out over this. I don't know how anyone gets this to work; my setup is certainly nothing atypical or weird. No VPN, either.  I wish I knew what I could try to change to see if it improved the problem, but I haven't a clue. After my earlier post, things settled down and starting running fine - though I didn't change a thing on my system at all. Now it told me there was an update, so I hit install - and back to this error. Non-stop. I don't even have any accessories installed - I haven't gotten that far! I guess I should give up. I'm a tech savvy power user (since 1987)...but clearly this is over my head.  :(

**Comment by jeffhatz** [comment]
@NorthernMan54 I've tracked down the issue to the "Split Tunnel" feature of the Private Internet Access VPN. Even though I have it set to only send traffic from specific apps traffic through the VPN, it was killing Homebridge which should have been routed like normal. Disabling that feature and sending all traffic through the VPN fixed it, and Homebridge now works as expected.

**Comment by ludufre** [comment]
If I may add my story. Here I'm started to have issues when I started to use pfSense. I have three IPSec VTI with route to specific IP ranges but in some way is interfering with mDNS broadcast. If i disable that IPSecs on pfSense, everythting became to work.

**Comment by NorthernMan54** [comment]
@jeffhatz @ludufre Tks for sharing the results of your investigations, hope this helps others with the issue.

**Comment by Th3Crow** [comment]
> @NorthernMan54 I've tracked down the issue to the "Split Tunnel" feature of the Private Internet Access VPN. 

OMG - I came here to post that I had finally found the problem...and it was exactly this, @jeffhatz !  Like you, I had it configured to use the VPN only for a handful of applications - so I didn't think it would be a problem.  Wish I could figure out how to use it in that configuration without interfering with Homebridge... ;)
