### ISSUE TITLE
Devices added in Homekit show "not responding" after an Upgrade/Update in Homebridge (restart as well)

### ISSUE THREAD

**Issue by jamesngob** [homebridge/homebridge#3686]
### Current Situation

I installed Homebridge server as VM, added few devices (Rachio controller) and a couple of Sonoff smart switches. I then added the Homebridge into Apple Homekit. Everything work great
However, everytime I update or upgrade the Homebridge, after a full restart then the devices added in Apple Homekit show "Not responding" and therefore, cannot be used any longer.
I tried to delete all caches, restart homebridge, not working
I tried to restart iPhone, not working
The only way so far is to remove the bridge (homebridge) from Apple Homekit then reset the Homebridge (via setting) and re-add it again back into the Apple Homekit, then all devices are working again until the next time I update or even restart Homebridge
Is there a way to solve this issue?

### Logs

```markdown
[8/30/2024, 11:20:14 AM]  <simulated-webhook> b728db03-7e94-4ddf-9ca3-eab9eef22d47 connected at Fri Aug 30 2024 11:20:14 GMT-0700 (Pacific Daylight Time)
[8/30/2024, 11:20:14 AM] <simulated-webhook> Standby Mode Off Scheduled waterings will now run on controller.
[8/30/2024, 11:20:14 AM] API rate limiting; call limit of 1646 remaining out of 1700 until reset at Fri Aug 30 2024 17:00:00 GMT-0700 (Pacific Daylight Time)
[8/30/2024, 11:20:14 AM]  Retrieved device state IDLE for Home with a DESIRED_ACTIVE state, running iro3-firmware-hk-14-645
[8/30/2024, 11:20:14 AM]  Configure Irrigation system for Home
[8/30/2024, 11:20:14 AM]  Configured zone-1 for Garden East-West with 3 min runtime
[8/30/2024, 11:20:14 AM]  Configured zone-2 for Grass Front - East with 3 min runtime
[8/30/2024, 11:20:14 AM]  Configured zone-3 for Grass Front - West with 3 min runtime
[8/30/2024, 11:20:14 AM] Configured zone-4 for Grass - Front with 3 min runtime
[8/30/2024, 11:20:14 AM] Configured zone-5 for Grass - Back  with 3 min runtime
[8/30/2024, 11:20:14 AM] Configured zone-6 for Grass - Front with 3 min runtime
[8/30/2024, 11:20:14 AM]  Configured zone-7 for Zone 7 with 3 min runtime
[8/30/2024, 11:20:14 AM]  Configured zone-8 for Zone 8 with 3 min runtime
[8/30/2024, 11:20:14 AM]  <simulated-webhook> d037e535-55b9-4291-a9b1-e9a35049fbd3 connected at Fri Aug 30 2024 11:20:14 GMT-0700 (Pacific Daylight Time)
[8/30/2024, 11:20:14 AM]  <simulated-webhook> Standby Mode Off  Scheduled waterings will now run on controller.
[8/30/2024, 11:20:14 AM]  API rate limiting; call limit of 1645 remaining out of 1700 until reset at Fri Aug 30 2024 17:00:00 GMT-0700 (Pacific Daylight Time)
[8/30/2024, 11:20:15 AM]  Rachio Platform finished loading controllers
[8/30/2024, 11:20:15 AM] [eWeLink] Fetching devices from eWeLink home/id
[617a33c6c15646000920ec7c].
[8/30/2024, 11:20:18 AM] [eWeLink] LAN monitoring started.
[8/30/2024, 11:20:18 AM] [eWeLink] initialising with options {"inUsePowerThreshold":0,"logging":"standard","showAs":"default"}.
[8/30/2024, 11:20:18 AM] [eWeLink]  initialised and LAN mode unavailable as not discovered/supported [1:BASICR2].
[8/30/2024, 11:20:18 AM] [eWeLink] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
[8/30/2024, 11:21:13 AM] [eWeLink]  current state [on].
[8/30/2024, 11:21:13 AM] [eWeLink]  has been reported [online] via LAN.
[8/30/2024, 11:22:36 AM] [eWeLink] current state [off].
```

### Configuration

```json
"bridge": {
        "name": "Homebridge",
        "username": "0E:5G:E4:38:AA:64",
        "port": 51403,
        "pin": "554-55-325",
        "advertiser": "bonjour-hap",
        "bind": [
            "ens160"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "xxx",
            "email": "xxx",
            "password": "xxx",
            "defaultRuntime": 1,
            "runtimeSource": 0,
            "useIrrigationDisplay": true,
            "showSimpleValve": false,
            "displayValveType": 1,
            "showIrrigation": true,
            "showBridge": false,
            "showFloodSensor": false,
            "showTempSensor": false,
            "showLimitsSensor": false,
            "showStandby": false,
            "showRunall": false,
            "showSchedules": false,
            "showAPIMessages": false,
            "showIncomingMessages": false,
            "showOutgoingMessages": false,
            "platform": "bhyve"
        },
        {
            "name": "xxx",
            "api_key": "9cwe3rdtea-cec8-4rr1-b79a-52d8d392a",
            "default_runtime": 3,
            "runtime_source": 0,
            "use_irrigation_display": true,
            "show_standby": false,
            "show_runall": false,
            "show_schedules": false,
            "internal_IP_address": "127.0.0.1",
            "auto_correct_IP": false,
            "external_webhook_port": 12453,
            "internal_webhook_port": 27546,
            "use_basic_auth": false,
            "delete_webhooks": false,
            "showAPIMessages": false,
            "showWebhookMessages": false,
            "valveType": 0,
            "showBridge": false,
            "showControllers": true,
            "showValves": true,
            "liveRefreshTimeout": 2,
            "liveRefreshRate": 20,
            "platform": "rachio"
        },
        {
            "name": "eWeLink",
            "username": "xxx",
            "password": "xxx",
            "mode": "auto",
            "language": "en",
            "platform": "eWeLink"
        }
    ]
}
```

### Environment

- OS: Ubuntu Focal 20.04.6 LTS
- Software: Homebridge v1.8.4
- Node: 20.17.0
- npm: 6.14.18

### Process Supervisor

hb-service

**Comment by jamesngob** [comment]
anyone is having the same behaviour like this?

**Comment by NorthernMan54** [comment]
You mentioned 'Homebridge server as VM', can you elaborate.

**Comment by jamesngob** [comment]
Oh, I run a version of Ubuntu server v22.04 as a virtual machine on Esxi 7.0. Then I installed Homebridge on this VM

**Comment by NorthernMan54** [comment]
Sounds like your VM setup is potentially an issue, what guide did you follow to set it up?

**Comment by jamesngob** [comment]
I installed Homebridge using this guide:
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux
As I mentioned, it is working perfectly after the installation. I added Homebridge into Apple Homekit app and been using it for the past 3 years. The issues is everytime I update/upgrade homebridge and need to restart the Homebridge and/or Ubuntu server, the devices that are added in Apple Homekit lost the connection to the Homebridge and therefore cannot be used.
The only way is to reset the homebridge server, delete homebridge in homekit and add it back again

**Comment by mpjalexander** [comment]
I have the same issue. It started happening a few weeks ago for me (I can’t remember exactly when). I’ve just set up a completely new Homebridge instance on a Raspberry Pi and hit the same problem almost straight away.

Not sure if it’s related, but when I installed the second public beta of iOS 18 on a spare iPhone over a month ago, it appeared to lose some of my HomeKit setup. Maybe that also started some other issues with HomeKit that’s resulting in problems with Homebridge?

However it started, I could really do with a solution as Homebridge is now completely broken for me!

**Comment by jamesngob** [comment]
anyone has this issue, please?

**Comment by jasontilley** [comment]
Also have this issue. As soon as updating to iOS 18 and Sequoia, HomeBridge is completely broken for me. No other changes. Tried deleting bridge in HomeKit and adding back but get "accessory not found". Even went as far as unpairing all bridges. Still no luck.

**Comment by jamesngob** [comment]
> Also have this issue. As soon as updating to iOS 18 and Sequoia, HomeBridge is completely broken for me. No other changes. Tried deleting bridge in HomeKit and adding back but get "accessory not found". Even went as far as unpairing all bridges. Still no luck.

What I did was remove the homebridge in Homekit; Reset the Homebridge server; then add it back again. Typically, it works after the whole thing done until next update

**Comment by dspadilla** [comment]
Having the same issue with Homebridge. Tried recommended method of removing HB from HK > Resetting HB > Adding HB back to HK, but still no luck.

Running HB as a Docker container. Environment is up to date. 

Anyone find a solution yet?

**Comment by cheme75** [comment]
I have similar issue after update from 1.83 to 1.84, hb on ubuntu 22.04/docker with 2 plugins. Lost connection to accessories, only thing that continued to work is a Wyze cam since I’m using scrypted for it. Something bogged down pc really bad at this point but resource usage looked low, so seemed odd. Anyway, wiped everything and started over. Fresh ubuntu install, fresh hb all looked ok then restored backup to get plugins and devices back. So far one plugin for blink is working normally, used my credentials and didn’t even need to re-do 2FA. But other plug-in, Wyze smart home is totally doa, errors authenticating. Updated plugin and still nothing. Wyze now uses an api ID and Key for 3rd party logins. Those same credentials work fine in the docker Wyze bridge so I reinstalled scrypted and it’s working fine, so clearly my credentials are valid. Meanwhile I’m not sure if it’s really a hb issue since blink works. Blink is not even a certified plugin. The Wyze plug-in is certified and it shows as hb 2 ready, but it’s not even working on 1.84! I think it’s the plug-in that’s faulty. I tried posting an issue and discussion on the plug-in git page but no replies. Maybe he stopped working on plug-in. Anyway, would be helpful if hb devs would push the devs with certified plugins to be more responsive to issues.

**Comment by dspadilla** [comment]
Thanks for the input @cheme75!

Sounds like you’re on to something since Wyze is working…

I’m trying to get Eufy working, which is a certified plugin and had updates when I started troubleshooting. 

Other forums mention mDNS issues. However, that wouldn’t make sense if it is only HB devices unable to be recognized in HK. All my other HK certified devices are working directly with HK via WiFi with no issues. This would rule out any network related issues. 

I haven’t tried rebuilding yet, but don’t know if it’s worth it considering your experience.

**Comment by cheme75** [comment]
> Thanks for the input @cheme75!
> 
> Sounds like you’re on to something since Wyze is working…
> 
> I’m trying to get Eufy working, which is a certified plugin and had updates when I started troubleshooting.
> 
> Other forums mention mDNS issues. However, that wouldn’t make sense if it is only HB devices unable to be recognized in HK. All my other HK certified devices are working directly with HK via WiFi with no issues. This would rule out any network related issues.
> 
> I haven’t tried rebuilding yet, but don’t know if it’s worth it considering your experience.

Wyze is working via its own app and in the docker Wyze bridge which uses the same credentials. So my Wyze db cam is working in hk using scrypted. Plus the blink hb plugin is working in hb and hk sees the cams. So I’d say hb is fine as far as I can see unless it has some code that is blocking the plug-in from authenticating with Wyze. My issue is the Wyze plugin for hb does not seem to be able to login to Wyze to detect my other devices - 2 bulbs and 2 plugs. Wyze allows 3rd parties via an api ID and Key and it only the Wyze plug-in since I updated HB to 1.84. It’s may be coincidence that the Wyze plugin crapped out apparently at the same time. It’s just odd that the Wyze bridge can authenticate, even after updates, but the Wyze plugin in HB cannot. I don’t use the camera ui plugin in HB for my cam since it was not a as good as scrypted. Now I wish scrypted could handle devices other than cams since the dev seems far more responsive.

**Comment by jasontilley** [comment]
For what's it's worth, I was able to solve my pairing problem today. I was using Homebrew's version of node, but in doing so, I was not able to give access to the local network in "Privacy and Settings" as advised here because it was missing as an option: https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS#macos-150--sequoia. I tried to figure out how do that manually, but I gave up and instead decided to uninstall my Homebrew version and use the Mac installer version recommended in the HomeBridge Wiki. I can finally connect HomeKit to HomeBridge again.

NOTE: I also had to change the path to node in /Library/LaunchDaemons/com.homebridge.server.plist

**Comment by cheme75** [comment]
> Thanks for the input @cheme75!
> 
> 
> 
> Sounds like you’re on to something since Wyze is working…
> 
> 
> 
> I’m trying to get Eufy working, which is a certified plugin and had updates when I started troubleshooting. 
> 
> 
> 
> Other forums mention mDNS issues. However, that wouldn’t make sense if it is only HB devices unable to be recognized in HK. All my other HK certified devices are working directly with HK via WiFi with no issues. This would rule out any network related issues. 
> 
> 
> 
> I haven’t tried rebuilding yet, but don’t know if it’s worth it considering your experience.

I forgot to ask - since your wyze plugin is working in HB - did you need to get new wyze credentials, api ID and key,  after you updated?  My ID and Key don't expire until May '25 but I can't think of any reason the plugin won't authenticate unless there is a glitch in the plugin.

**Comment by dspadilla** [comment]
The only HB plugin I’m using is Eufy. I’m not using any Wyze devices. I just switched out all my lights and switches to Meross HK compatible.

**Comment by cheme75** [comment]
> The only HB plugin I’m using is Eufy. I’m not using any Wyze devices. I just switched out all my lights and switches to Meross HK compatible. 

Oh, ok. Thought it was wyze problem for you too. I'm done with wyze other than the few things I got that still work. Was handy to have lights in HK, but ultimately it's not a big deal. The db cam works through scrypted really well. I create the RTSP stream with docker wyze bridge which also has a nice web ui. Since I got a basic iCloud acct anyway, it gives me person detection that wyze charges extra to get. Since I setup HB to try the blink plugin which does work ok, I figured I'd add the wyze bulbs and plugs. I'll eventually try a new ID and key but if it fails, not that big a deal. Just irritating all was fine for quite some time.

**Comment by mcmara** [comment]
Same here, after upgrading HB to V1.9.0. So reinstalled HB on one Debian server in my network, and now I'm having troubles to add it to HomeKit. From my iPhone, after scanning the QR code, I get Accessory not found. Both the iPhone and the server are on the same VLAN. The iPhone is using WiFi through a set of Cisco APs controlled by the WLC 2504, while the Debian server is directly wired into the router (pfsense). HB is invisible to the iPhone. Tried all the advertisers, with no luck. No errors in the HB logs: the service seems simply invisible. Ah, tried to force the network interface as well: no luck.
